// Builds trusted, platform-neutral production models. Never compiles a user's package.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
let ts;
try{ts=require('typescript');}catch{ts=require(process.env.FRIDGE_TYPESCRIPT||'/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript');}
const root=path.resolve(__dirname,'../entry/src/main/ets/model'),modules=new Map();
const entries=['TemplatePackage','AlbumLayout','AlbumRotation','CardDepth','ContourPath','CloudReadingGeometry','CanvasLayout','ContourRegistry','EdgeAttachment','CapabilityData','BatteryPresentation','MicaGeometry','MicaMaterialStudy','PaperTextWidth','CapabilityCalendar','SubjectGeometry','EditorVisualChoices'];
function collect(name){
 if(modules.has(name))return;
 if(!/^[A-Za-z][A-Za-z0-9]*$/.test(name))throw Error('Invalid dependency');
 const source=fs.readFileSync(path.join(root,name+'.ets'),'utf8');
 const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 if(/require\(["'](?!\.\/)/.test(code))throw Error(name+' has a platform dependency; split the pure model first');
 modules.set(name,{source,code});
 for(const dep of code.matchAll(/require\(["']\.\/([A-Za-z][A-Za-z0-9]*)["']\)/g))collect(dep[1]);
}
entries.forEach(collect);
const sourceHash=crypto.createHash('sha256');
for(const [name,{source}] of [...modules].sort(([a],[b])=>a.localeCompare(b)))sourceHash.update(name+'\0'+source+'\0');
const fingerprint=sourceHash.digest('hex');
const functions=[...modules].map(([name,{code}])=>JSON.stringify(name)+':function(require,module,exports){\n'+code+'\n}').join(',\n');
const bundle='// Generated by build.cjs from production pure models. Do not hand-edit.\n'+
 '(function(global){"use strict";const modules={'+functions+'};const cache={};function load(name){if(cache[name])return cache[name].exports;if(!modules[name])throw Error("Unknown shared model "+name);const module={exports:{}};cache[name]=module;modules[name](s=>load(s.replace(/^\\.\\//,"")),module,module.exports);return module.exports;}global.FridgeCore={load,sourceFingerprint:'+JSON.stringify(fingerprint)+'};})(globalThis);\n';
const target=path.join(__dirname,'shared-models.js');
const nativeTarget=path.join(root,'PreviewDesignContract.ets');
const nativeSource='/** Generated by previewer/build.cjs: shared production model identity, not a pixel-parity promise. */\nexport const PREVIEW_DESIGN_FINGERPRINT:string='+JSON.stringify(fingerprint)+';\n';
const mediaRoot=path.resolve(root,'../../resources/base/media');
const materials={};
for(const name of fs.readdirSync(mediaRoot).filter(n=>/^reading_.*\.png$/.test(n)).sort())materials[name.slice(0,-4)]='data:image/png;base64,'+fs.readFileSync(path.join(mediaRoot,name)).toString('base64');
const materialBundle='// Generated from the same offline app materials.\nglobalThis.FridgeMaterials='+JSON.stringify(materials)+';\n';
const materialTarget=path.join(__dirname,'shared-materials.js');
// Authoring metadata is an external release artifact, never an invented v1 package field.
const vm=require('node:vm'),context=vm.createContext({});vm.runInContext(bundle,context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'capabilities.js'),'utf8'),context);
const schema=context.FridgeCore.load('CardSchema'),policy=context.FridgeCore.load('ReadingStylePolicy');
const repository=path.resolve(__dirname,'..');
const hashFiles=files=>{const hash=crypto.createHash('sha256');for(const file of files.sort())hash.update(file+'\0'+fs.readFileSync(path.join(repository,file))+'\0');return hash.digest('hex');};
const nativeViews=['CardFace','CardCanvas','CapBlockView','ReadingBacking','ReadingEdgeBacking','ReadingHook','SummaryCapability','TimetableCapability','AlbumCapability','BatteryCapability','CanvasBackdrop','EditorVisualChoices'];
const schemaSource=modules.get('CardSchema').source;
function fields(declaration){const body=schemaSource.split(declaration)[1]?.split('\n}')[0];if(!body)throw Error('Authoring declaration changed: '+declaration);return [...body.matchAll(/^\s*([a-zA-Z][\w]*)\??\s*:/gm)].map(match=>match[1]);}
const contract={
 contractVersion:1,skillContractVersion:4,app:JSON.parse(fs.readFileSync(path.join(repository,'AppScope/app.json5'),'utf8')).app,
 package:{format:'fridgememo-template',version:2,readVersions:[1,2],schemaVersion:2,kinds:['card','canvas'],htmlSupported:true,htmlMode:'static-source-and-cache/native-capability',htmlTemplateVersion:1},
 identity:{models:fingerprint,materials:crypto.createHash('sha256').update(materialBundle).digest('hex'),browserAdapter:hashFiles(['previewer/renderer.js','previewer/capabilities.js']),nativeViews:hashFiles(nativeViews.map(name=>'entry/src/main/ets/views/'+name+'.ets'))},
 coordinates:{boardWidth:schema.BOARD_W,legacyPositionHeight:schema.BOARD_H,cardSizeUnits:'board_width',elementUnits:'card_fraction',rotationUnits:'degrees'},
 limits:{canvasCards:context.FridgeCore.load('CanvasCapacity').CANVAS_CARD_LIMIT},
 design:{readingMaterials:{default:'paper',options:['paper','matte'],hostOwned:true,experimentalField:'readingMaterialStudy',persistExperimental:false},canvasBackgroundModes:['solid','smart','blend','photo','preset','transparent'],transparentFrame:{default:'auto',options:['auto','light','dark','none'],hollow:true},relief:{side:1.35,castRadius:9,castY:4.5,contactRadius:1.6,contactY:.6},transparentForm:{minimumApi:22,requiresManualEntitlement:true,minimumVisibleFraction:.1},binding:'current-host',persistedProfileField:false,rectRadius:schema.RECT_CORNER_RADIUS,album:{presentations:['cover','classic','row'],inset:schema.ALBUM_INSET,coverRadius:schema.ALBUM_CORNER_RADIUS,cardRadius:schema.ALBUM_CARD_CORNER_RADIUS,squareCover:true}},
 capabilities:Array.from(schema.CAPABILITIES,kind=>({kind,readingStyles:Array.from(policy.readingStyles(kind)),legacyDefault:policy.defaultReadingStyle(kind),preferredStyle:policy.preferredReadingStyle(kind)})),
 fields:{state:fields('export class FridgeState {'),card:fields('export class FridgeCard {'),capability:fields('export interface CapBlock {'),element:[...fields('export class ElementBox {'),...fields('export class CanvasElement extends ElementBox {')]},
 retiredCapabilityFields:['url','field','sourceConfigured','parcels','parcelPlace','temp','desc'],
 preview:{supportedCapabilities:[...context.FridgeReadouts.supportedKinds,'album'],staticFrame:true,systemSymbols:'vector-substitutes',fontParity:false,actualFormVerified:false}
};
const contractJSON=JSON.stringify(contract,null,2)+'\n';
const generated=[
 [target,bundle],[nativeTarget,nativeSource],[materialTarget,materialBundle],
 [path.join(__dirname,'design-contract.js'),'// Generated release contract. Do not hand-edit.\nglobalThis.FridgeDesignContract='+JSON.stringify(contract)+';\n'],
 [path.join(repository,'skills/fridge-create/references/design-contract.json'),contractJSON]
];
if(process.argv.includes('--check')){
 if(generated.some(([file,source])=>!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==source)){console.error('Preview models/materials/design contract are stale. Run node previewer/build.cjs');process.exitCode=1;}
 else console.log('PASS preview bundle matches production models '+fingerprint.slice(0,12));
}else{for(const [file,source] of generated)fs.writeFileSync(file,source);console.log('Built '+modules.size+' pure production models and release contract '+fingerprint.slice(0,12));}
