// Builds trusted, platform-neutral production models. Never compiles a user's package.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
let ts;
try{ts=require('typescript');}catch{ts=require(process.env.FRIDGE_TYPESCRIPT||'/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript');}
const root=path.resolve(__dirname,'../entry/src/main/ets/model'),modules=new Map();
const entries=['TemplatePackage','AlbumLayout','AlbumRotation','CardDepth','ContourPath','CloudReadingGeometry'];
function collect(name){
 if(modules.has(name))return;
 if(!/^[A-Za-z][A-Za-z0-9]*$/.test(name))throw Error('Invalid dependency');
 const source=fs.readFileSync(path.join(root,name+'.ets'),'utf8');
 const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 if(/require\(["'](?!\.\/)/.test(code))throw Error(name+' has a platform dependency; split the pure model first');
 modules.set(name,{source,code});
 for(const dep of code.matchAll(/require\(["']\.\/([A-Za-z][A-Za-z0-9]*)["']\)/g))collect(dep[1]);
}
entries.forEach(collect);
const sourceHash=crypto.createHash('sha256');
for(const [name,{source}] of [...modules].sort(([a],[b])=>a.localeCompare(b)))sourceHash.update(name+'\0'+source+'\0');
const fingerprint=sourceHash.digest('hex');
const functions=[...modules].map(([name,{code}])=>JSON.stringify(name)+':function(require,module,exports){\n'+code+'\n}').join(',\n');
const bundle='// Generated by build.cjs from production pure models. Do not hand-edit.\n'+
 '(function(global){"use strict";const modules={'+functions+'};const cache={};function load(name){if(cache[name])return cache[name].exports;if(!modules[name])throw Error("Unknown shared model "+name);const module={exports:{}};cache[name]=module;modules[name](s=>load(s.replace(/^\\.\\//,"")),module,module.exports);return module.exports;}global.FridgeCore={load,sourceFingerprint:'+JSON.stringify(fingerprint)+'};})(globalThis);\n';
const target=path.join(__dirname,'shared-models.js');
const nativeTarget=path.join(root,'PreviewDesignContract.ets');
const nativeSource='/** Generated by previewer/build.cjs: shared production model identity, not a pixel-parity promise. */\nexport const PREVIEW_DESIGN_FINGERPRINT:string='+JSON.stringify(fingerprint)+';\n';
if(process.argv.includes('--check')){
 if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==bundle||!fs.existsSync(nativeTarget)||fs.readFileSync(nativeTarget,'utf8')!==nativeSource){console.error('Preview models are stale. Run node previewer/build.cjs');process.exitCode=1;}
 else console.log('PASS preview bundle matches production models '+fingerprint.slice(0,12));
}else{fs.writeFileSync(target,bundle);fs.writeFileSync(nativeTarget,nativeSource);console.log('Built '+modules.size+' pure production models '+fingerprint.slice(0,12));}
