// Generated by build.cjs from production pure models. Do not hand-edit.
(function(global){"use strict";const modules={"TemplatePackage":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.remapSceneSchedules = exports.fitImportedCanvas = exports.importedCards = exports.readPackage = exports.packageScene = void 0;
const CardSchema_1 = require("./CardSchema");
const CanvasCapacity_1 = require("./CanvasCapacity");
function packageScene(json, cardId) {
    const state = (0, CardSchema_1.normalizeState)(JSON.parse(json));
    if (cardId.length > 0) {
        state.cards = state.cards.filter((c) => c.id === cardId);
        if (state.cards.length !== 1)
            throw new Error('卡片不存在');
        state.cards[0].groupId = '';
        state.sceneLayouts = [];
        state.sceneRules = [];
        state.sceneBaseLayoutId = '';
        state.background = (0, CardSchema_1.defaultState)().background;
    }
    state.canvasId = 'canvas_main';
    for (const card of state.cards) {
        const cap = card.capability;
        if (cap?.k === 'battery') {
            cap.percent = -1;
            cap.charging = false;
            cap.chargeState = '';
            cap.updatedAt = 0;
            cap.attemptedAt = 0;
        }
        if (cap?.k === 'agenda' && cap.agendaSource === 'system') {
            cap.events = [];
            cap.updatedAt = 0;
            cap.attemptedAt = 0;
        }
    }
    return { format: 'fridgememo-template', version: 1, kind: cardId.length > 0 ? 'card' : 'canvas', state: state, assets: [] };
}
exports.packageScene = packageScene;
function readPackage(json) {
    if (json.length > 90 * 1024 * 1024)
        throw new Error('作品包超过大小限制');
    const raw = JSON.parse(json);
    if (raw.format !== 'fridgememo-template' || raw.version !== 1 || !['card', 'canvas'].includes(raw.kind) || raw.state?.schemaVersion !== 2 || !Array.isArray(raw.state?.cards) || raw.state.cards.length > 128 || !Array.isArray(raw.assets) || raw.assets.length > 256)
        throw new Error('不是支持的作品包');
    (0, CanvasCapacity_1.assertCanvasCapacity)(0, raw.state.cards.length);
    if (raw.kind === 'card' && raw.state.cards.length !== 1)
        throw new Error('卡片包内容不完整');
    const keys = [];
    for (const a of raw.assets) {
        if (typeof a.key !== 'string' || keys.includes(a.key) || !/^asset:\/\/\d+$/.test(a.key) || !/^\.(png|jpg|jpeg|gif|webp)$/.test(a.extension) || typeof a.data !== 'string' || a.data.length > 32 * 1024 * 1024)
            throw new Error('作品图片无效');
        keys.push(a.key);
    }
    const refs = [raw.state.background?.src ?? '', raw.state.background?.photo ?? ''];
    for (const c of raw.state.cards) {
        refs.push(c.cutout ?? '', c.capability?.albumCover ?? '', c.capability?.albumBackground ?? '');
        for (const a of c.capability?.albumItems ?? [])
            refs.push(a.cover, a.background);
        for (const el of c.elements ?? [])
            refs.push(el.src ?? '');
    }
    if (refs.some((src) => src.length > 0 && !keys.includes(src)))
        throw new Error('作品图片引用不完整');
    // Normal runtime schemas intentionally reject package-local asset URIs.
    // Normalize their temporary file representation, then restore the validated keys.
    const swap = (from, to) => {
        const bg = raw.state.background;
        if (bg !== undefined) {
            if (bg.src === from)
                bg.src = to;
            if (bg.photo === from)
                bg.photo = to;
        }
        for (const c of raw.state.cards) {
            if (c.cutout === from)
                c.cutout = to;
            if (c.capability) {
                if (c.capability.albumCover === from)
                    c.capability.albumCover = to;
                if (c.capability.albumBackground === from)
                    c.capability.albumBackground = to;
                for (const a of c.capability.albumItems ?? []) {
                    if (a.cover === from)
                        a.cover = to;
                    if (a.background === from)
                        a.background = to;
                }
            }
            for (const el of c.elements ?? [])
                if (el.src === from)
                    el.src = to;
        }
    };
    for (const c of raw.state.cards) {
        if (typeof c.id !== 'string' || (c.elements ?? []).length > 128 || (c.outline ?? []).length > 128 || (c.outline ?? []).reduce((sum, row) => sum + row.length, 0) > 16384)
            throw new Error('作品图层或轮廓过多');
    }
    for (const key of keys)
        swap(key, 'file:///template/' + key.slice(8));
    raw.state = (0, CardSchema_1.normalizeState)(raw.state);
    for (const key of keys)
        swap('file:///template/' + key.slice(8), key);
    return raw;
}
exports.readPackage = readPackage;
/** Remap every identifier; importing twice never aliases a card, element or group. */
function importedCards(state, newId) {
    const cards = (0, CardSchema_1.normalizeState)(JSON.parse(JSON.stringify(state))).cards, groups = new Map();
    for (const c of cards) {
        c.id = newId();
        if (c.groupId.length > 0) {
            if (!groups.has(c.groupId))
                groups.set(c.groupId, newId());
            c.groupId = groups.get(c.groupId) ?? '';
        }
        c.elements.forEach(el => { el.id = newId(); });
        c.renderContourKey = '';
    }
    return cards;
}
exports.importedCards = importedCards;
/** Fit a shared composition as one scene; do not stretch its relative card positions. */
function fitImportedCanvas(cards, sourceAspect, targetAspect) {
    const sourceH = CardSchema_1.BOARD_W / sourceAspect, targetH = CardSchema_1.BOARD_W / targetAspect;
    const scale = Math.min(1, targetH / sourceH), left = CardSchema_1.BOARD_W * (1 - scale) / 2, top = (targetH - sourceH * scale) / 2;
    for (const c of cards) {
        c.x = c.x * scale + left;
        c.y = (c.y / CardSchema_1.BOARD_H * sourceH * scale + top) / targetH * CardSchema_1.BOARD_H;
        c.w *= scale;
        c.h *= scale;
    }
}
exports.fitImportedCanvas = fitImportedCanvas;
/** Layouts travel with a canvas. Imported schedules are opt-in; external canvas targets cannot travel in a single document. */
function remapSceneSchedules(state, cards, newId, targetAspect) {
    const cardIds = new Map();
    state.cards.forEach((c, i) => { if (cards[i])
        cardIds.set(c.id, cards[i].id); });
    const layoutIds = new Map(), sourceH = CardSchema_1.BOARD_W / state.canvasAspect, targetH = CardSchema_1.BOARD_W / targetAspect, scale = Math.min(1, targetH / sourceH), left = CardSchema_1.BOARD_W * (1 - scale) / 2, top = (targetH - sourceH * scale) / 2;
    state.sceneLayouts.forEach((layout) => { const old = layout.id; layout.id = newId(); layoutIds.set(old, layout.id); layout.placements = layout.placements.filter(p => cardIds.has(p.id)); layout.placements.forEach(p => { p.id = cardIds.get(p.id); p.x = p.x * scale + left; p.y = (p.y / CardSchema_1.BOARD_H * sourceH * scale + top) / targetH * CardSchema_1.BOARD_H; p.w *= scale; p.h *= scale; }); });
    state.sceneBaseLayoutId = layoutIds.get(state.sceneBaseLayoutId) ?? '';
    state.sceneRules = state.sceneRules.filter(r => r.kind !== 'canvas' && (r.kind === 'layout' ? layoutIds.has(r.targetId) : cardIds.has(r.targetId)));
    state.sceneRules.forEach(r => { r.id = newId(); r.targetId = (r.kind === 'layout' ? layoutIds : cardIds).get(r.targetId); r.enabled = false; r.dismissed = ''; r.createdAt = Date.now(); });
}
exports.remapSceneSchedules = remapSceneSchedules;

},
"CardSchema":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.normalizeCapability = exports.contrastingInk = exports.serializeDoorCards = exports.serializeFaceCards = exports.normalizeState = exports.normalizeElement = exports.localImageSource = exports.normalizeBox = exports.bounded = exports.defaultState = exports.cardCornerRadius = exports.shapeRadius = exports.materialColors = exports.typeLabel = exports.FridgeState = exports.normalizeBackground = exports.CanvasBackground = exports.BackgroundAnchor = exports.DoorState = exports.FridgeCard = exports.CanvasElement = exports.ElementBox = exports.CAPABILITIES = exports.CapType = exports.MIN_SUBJECT_EDGE = exports.ALBUM_CARD_CORNER_RADIUS = exports.ALBUM_CORNER_RADIUS = exports.ALBUM_INSET = exports.RECT_CORNER_RADIUS = exports.MIN_CARD_EDGE = exports.BOARD_H = exports.BOARD_W = void 0;
const ReadingStylePolicy_1 = require("./ReadingStylePolicy");
const SceneScheduleSchema_1 = require("./SceneScheduleSchema");
const TimeCapabilities_1 = require("./TimeCapabilities");
const HolidayCalendar_1 = require("./HolidayCalendar");
/** Pure, versioned schema shared by the app and FormKit renderer. */
exports.BOARD_W = 344;
exports.BOARD_H = 470;
/** Artwork bounds only; capability readability is enforced separately by layout. */
exports.MIN_CARD_EDGE = 32;
exports.RECT_CORNER_RADIUS = 16;
exports.ALBUM_INSET = 4.9;
exports.ALBUM_CORNER_RADIUS = 14;
exports.ALBUM_CARD_CORNER_RADIUS = 20;
exports.MIN_SUBJECT_EDGE = 16;
class CapType {
}
exports.CapType = CapType;
CapType.CLOCK = 'clock';
CapType.DATE = 'date';
CapType.CALENDAR = 'calendar';
CapType.COUNTDOWN = 'countdown';
CapType.ANNIVERSARY = 'anniversary';
CapType.DAY_PROGRESS = 'dayprogress';
CapType.YEAR_PROGRESS = 'yearprogress';
exports.CAPABILITIES = ['clock', 'date', 'calendar', 'countdown', 'anniversary', 'dayprogress', 'yearprogress', 'battery', 'agenda', 'timetable', 'worldclock', 'lunar', 'album'];
class ElementBox {
    constructor() {
        this.x = 0.1;
        this.y = 0.12;
        this.w = 0.8;
        this.h = 0.7;
        this.rot = 0;
        this.opacity = 1;
    }
}
exports.ElementBox = ElementBox;
class CanvasElement extends ElementBox {
    constructor() {
        super(...arguments);
        this.id = '';
        this.kind = 'text'; // text | image | shape
        this.text = '';
        this.src = '';
        this.animated = false;
        this.fs = 18;
        this.color = '';
        this.bold = false;
        this.align = 'left';
        this.behindCapability = false;
        this.primitive = 'rect'; // rect | circle | line
    }
}
exports.CanvasElement = CanvasElement;
class FridgeCard {
    constructor() {
        this.groupId = '';
        this.id = '';
        this.x = 24;
        this.y = 32;
        this.w = 180;
        this.h = 180;
        this.rot = 0;
        this.z = 1;
        this.shape = 'rect';
        this.frame = false;
        this.material = 'white';
        this.paper = '';
        this.ink = '';
        this.capability = null;
        this.capBox = new ElementBox();
        this.capFree = false; // Manual foreground placement uses the whole card box, not its silhouette.
        this.elements = [];
        this.subjectPhoto = false;
        this.subjectBorder = true;
        this.subjectAspect = 1;
        this.subjectInk = '#262824';
        this.subjectVersion = 0;
        this.cutout = ''; // transparent subject PNG, also the alpha mask
        this.outline = [];
        this.renderContourKey = '';
        this.inDoor = false;
    }
}
exports.FridgeCard = FridgeCard;
class DoorState {
    constructor() {
        this.reveal = '07:30';
        this.open = false;
    }
}
exports.DoorState = DoorState;
class BackgroundAnchor {
    constructor() {
        this.x = .5;
        this.y = .5;
        this.color = '#E9E5DF';
        this.weight = 1;
    }
}
exports.BackgroundAnchor = BackgroundAnchor;
class CanvasBackground {
    constructor() {
        this.mode = 'solid';
        this.color = '#FFFFFF';
        this.src = '';
        this.photo = '';
        this.palette = [];
        this.anchors = [];
        this.signature = '';
    }
}
exports.CanvasBackground = CanvasBackground;
function normalizeBackground(raw) {
    const bg = new CanvasBackground();
    if (raw === undefined || raw === null)
        return bg;
    bg.mode = ['solid', 'smart', 'blend', 'photo', 'preset'].includes(raw.mode) ? raw.mode : 'solid';
    bg.color = /^#[0-9a-fA-F]{6}$/.test(raw.color ?? '') ? raw.color : '#FFFFFF';
    bg.src = (raw.src ?? '').startsWith('file://') || (raw.src ?? '').startsWith('memory://') ? raw.src : '';
    bg.photo = (raw.photo ?? '').startsWith('file://') ? raw.photo : '';
    bg.palette = (Array.isArray(raw.palette) ? raw.palette : []).filter((c) => /^#[0-9a-fA-F]{6}$/.test(c)).slice(0, 6);
    bg.anchors = (Array.isArray(raw.anchors) ? raw.anchors : []).slice(0, 12).filter((a) => a !== null && /^#[0-9a-fA-F]{6}$/.test(a.color)).map((a) => ({ x: bounded(a.x, 0, 1, .5), y: bounded(a.y, 0, 1, .5), color: a.color, weight: bounded(a.weight, .05, 8, 1) }));
    bg.signature = typeof raw.signature === 'string' ? raw.signature : '';
    return bg;
}
exports.normalizeBackground = normalizeBackground;
class FridgeState {
    constructor() {
        this.sceneLayouts = [];
        this.sceneRules = [];
        this.sceneBaseLayoutId = ''; // Empty = current homepage; selecting a saved normal layout applies its geometry.
        this.schemaVersion = 2;
        this.canvasId = 'canvas_main';
        this.background = new CanvasBackground();
        this.canvasAspect = 1;
        this.canvasDimension = '4*4';
        this.fridge = 'board';
        this.door = new DoorState();
        this.maxZ = 10;
        this.cards = [];
    }
}
exports.FridgeState = FridgeState;
function typeLabel(k) {
    const index = exports.CAPABILITIES.indexOf(k);
    const names = ['时间', '日期', '台历', '倒计时', '纪念日', '今日进度', '年度进度', '本机电量', '日程', '课程表', '世界时钟', '农历', '音乐专辑'];
    return index >= 0 ? names[index] : '自定义';
}
exports.typeLabel = typeLabel;
function materialColors(material, paper = '', ink = '') {
    let base = ['#FFFFFF', '#262824'];
    if (material === 'cream')
        base = ['#F3EEDC', '#454035'];
    if (material === 'kraft')
        base = ['#DED0B8', '#433B31'];
    if (material === 'mint')
        base = ['#E1E9DF', '#344237'];
    if (material === 'blue')
        base = ['#E2E8EE', '#354553'];
    if (material === 'pink')
        base = ['#EEDFE0', '#543C40'];
    if (material === 'dark')
        base = ['#292A28', '#F4F3EF'];
    return [/^#[0-9a-fA-F]{6}$/.test(paper) ? paper : base[0], /^#[0-9a-fA-F]{6}$/.test(ink) ? ink : base[1]];
}
exports.materialColors = materialColors;
function shapeRadius(shape, scale = 1) {
    if (shape === 'round')
        return '50%';
    if (shape === 'pill')
        return 999;
    if (shape === 'blob')
        return { topLeft: '28%', topRight: '12%', bottomLeft: '18%', bottomRight: '26%' };
    return shape === 'subject' ? 0 : exports.RECT_CORNER_RADIUS * scale;
}
exports.shapeRadius = shapeRadius;
/** Album geometry approved in the interactive demo; shared by app, export and widget. */
function cardCornerRadius(card, scale = 1) {
    return card.capability?.k === 'album' ? exports.ALBUM_CARD_CORNER_RADIUS * scale : shapeRadius(card.shape, scale);
}
exports.cardCornerRadius = cardCornerRadius;
function defaultState() { return new FridgeState(); }
exports.defaultState = defaultState;
function bounded(value, min, max, fallback) {
    return Math.max(min, Math.min(max, Number.isFinite(value) ? value : fallback));
}
exports.bounded = bounded;
function normalizeBox(raw) {
    const box = new ElementBox();
    box.w = bounded(raw?.w, 0.1, 1, 0.8);
    box.h = bounded(raw?.h, 0.08, 1, 0.7);
    box.x = bounded(raw?.x, 0, 1 - box.w, 0.1);
    box.y = bounded(raw?.y, 0, 1 - box.h, 0.12);
    box.rot = bounded(raw?.rot, -180, 180, 0);
    box.opacity = bounded(raw?.opacity, 0.1, 1, 1);
    return box;
}
exports.normalizeBox = normalizeBox;
/** Runtime images must never trigger HTTP requests, including migrated artwork. */
function localImageSource(value) {
    return typeof value === 'string' && (value.startsWith('file://') || value.startsWith('memory://')) ? value : '';
}
exports.localImageSource = localImageSource;
function normalizeElement(raw, clippedSubject = false) {
    const box = normalizeBox(raw);
    const el = new CanvasElement();
    el.id = raw.id;
    el.kind = ['text', 'image', 'shape'].includes(raw.kind) ? raw.kind : 'text';
    el.x = clippedSubject ? bounded(raw.x, -8, 8, box.x) : box.x;
    el.y = clippedSubject ? bounded(raw.y, -8, 8, box.y) : box.y;
    el.w = clippedSubject ? bounded(raw.w, .01, 16, box.w) : box.w;
    el.h = clippedSubject ? bounded(raw.h, .01, 16, box.h) : box.h;
    el.rot = box.rot;
    el.opacity = box.opacity;
    el.text = raw.text ?? '';
    el.src = localImageSource(raw.src);
    el.animated = raw.animated === true;
    el.fs = bounded(raw.fs, 10, 64, 18);
    el.color = raw.color ?? '';
    el.behindCapability = raw.behindCapability ?? false;
    el.bold = raw.bold ?? false;
    el.align = raw.align ?? 'left';
    el.primitive = raw.primitive ?? 'rect';
    return el;
}
exports.normalizeElement = normalizeElement;
function legacyElement(cap, id, index, count) {
    const el = new CanvasElement();
    el.id = id + '_element_' + index;
    el.y = index / count;
    el.h = 1 / count;
    el.x = 0.08;
    el.w = 0.84;
    if (cap.k === 'photo') {
        el.kind = 'image';
        el.src = localImageSource(cap.seed);
        el.x = 0;
        el.w = 1;
    }
    else {
        el.text = cap.k === 'np' ? [cap.title ?? '', cap.artist ?? ''].filter((v) => v.length > 0).join('\n') : (cap.text ?? '');
        el.fs = cap.fs ?? 18;
        el.align = cap.align ?? 'left';
        el.bold = cap.bold ?? false;
    }
    return el;
}
function normalizeState(raw) {
    const state = new FridgeState();
    state.canvasId = typeof raw.canvasId === 'string' && /^[a-zA-Z0-9_-]{1,96}$/.test(raw.canvasId) ? raw.canvasId : 'canvas_main';
    state.background = normalizeBackground(raw.background);
    state.door = raw.door ?? new DoorState();
    state.canvasDimension = ['2*4', '4*4', '6*4'].includes(raw.canvasDimension) ? raw.canvasDimension : '4*4';
    state.canvasAspect = bounded(raw.canvasAspect, .3, 3, 1);
    state.sceneLayouts = (0, SceneScheduleSchema_1.normalizeSceneLayouts)(raw.sceneLayouts);
    state.sceneRules = (0, SceneScheduleSchema_1.normalizeSceneRules)(raw.sceneRules);
    state.sceneBaseLayoutId = state.sceneLayouts.some(s => s.id === raw.sceneBaseLayoutId) ? raw.sceneBaseLayoutId : '';
    state.maxZ = bounded(raw.maxZ, 0, Number.MAX_SAFE_INTEGER, 10);
    for (const source of (Array.isArray(raw.cards) ? raw.cards : [])) {
        if (source === null || typeof source.id !== 'string')
            continue;
        const card = new FridgeCard();
        card.id = source.id;
        card.groupId = typeof source.groupId === 'string' ? source.groupId.slice(0, 96) : '';
        card.w = bounded(source.w, source.shape === 'subject' ? exports.MIN_SUBJECT_EDGE : exports.MIN_CARD_EDGE, 320, 180);
        card.h = bounded(source.h, source.shape === 'subject' ? exports.MIN_SUBJECT_EDGE : exports.MIN_CARD_EDGE, 420, 180);
        // Validate finite coordinates here. Rotated/host-aware recovery belongs to
        // the whole canvas, where grouping and the actual aspect are available.
        card.x = bounded(source.x, -840, exports.BOARD_W + 840, 24);
        card.y = bounded(source.y, -840, exports.BOARD_H + 840, 32);
        if (raw.schemaVersion !== 2) {
            card.x = bounded(source.x, -card.w + Math.min(32, card.w * .2), exports.BOARD_W - Math.min(32, card.w * .2), 24);
            card.y = bounded(source.y, -card.h + Math.min(32, card.h * .2), exports.BOARD_H - Math.min(32, card.h * .2), 32);
        }
        card.rot = bounded(source.rot, -180, 180, 0);
        card.z = bounded(source.z, 0, Number.MAX_SAFE_INTEGER, 1);
        card.shape = source.shape ?? 'rect';
        card.frame = source.frame ?? false;
        card.material = source.material ?? 'white';
        card.paper = source.paper ?? '';
        card.ink = source.ink ?? '';
        card.inDoor = source.inDoor ?? false;
        card.cutout = (source.cutout ?? '').startsWith('file://') || (source.cutout ?? '').startsWith('memory://') ? source.cutout : '';
        card.subjectBorder = true;
        card.subjectPhoto = source.subjectPhoto ?? false;
        card.subjectVersion = source.subjectVersion ?? 0;
        card.subjectInk = source.subjectInk ?? '#262824';
        card.subjectAspect = source.subjectAspect ?? 1;
        card.outline = Array.isArray(source.outline) ? source.outline : [];
        card.capBox = normalizeBox(source.capBox);
        card.capBox.rot = 0;
        card.capFree = source.capFree === true;
        card.elements = Array.isArray(source.elements) ? source.elements.filter((el) => el !== null && typeof el.id === 'string').map((el) => normalizeElement(el, card.shape === 'subject')) : [];
        const caps = raw.schemaVersion === 2 ? (source.capability !== null && source.capability !== undefined ? [source.capability] : []) : (source.caps ?? []);
        state.cards.push(card);
        state.maxZ = Math.max(state.maxZ, card.z);
        for (let i = 0; i < caps.length; i++) {
            const cap = caps[i];
            if (cap === null || typeof cap.k !== 'string')
                continue;
            // Retired capabilities leave the user's card artwork intact.
            if (cap.k === 'weather' || cap.k === 'parcel')
                continue;
            if (cap.k === 'fetch') {
                // Keep the last visible result as artwork, without retaining a network source.
                if (typeof cap.value === 'string' && cap.value.length > 0) {
                    const cached = legacyElement({ k: 'text', text: [cap.title ?? '', cap.value + (cap.unit ?? '')].filter((v) => v.length > 0).join('\n') }, card.id, i, caps.length);
                    if (raw.schemaVersion === 2) {
                        const box = normalizeBox(source.capBox);
                        cached.x = box.x;
                        cached.y = box.y;
                        cached.w = box.w;
                        cached.h = box.h;
                    }
                    cached.id = card.id + '_cached_value_' + i;
                    while (card.elements.some((el) => el.id === cached.id))
                        cached.id += '_';
                    card.elements.push(cached);
                }
                continue;
            }
            if (exports.CAPABILITIES.includes(cap.k)) {
                if (card.capability === null) {
                    card.capability = normalizeCapability(cap);
                    if (card.capFree && ['cloud', 'bare', 'badge', 'sticker', 'space', 'tag', 'dock'].includes(card.capability.readingBlend ?? '')) {
                        if (card.capability.readingBlend === 'sticker')
                            card.capBox.w = bounded(source.capBox?.w, .01, 3, .8);
                        card.capBox.x = bounded(source.capBox?.x, -2, 2, .1);
                        card.capBox.y = bounded(source.capBox?.y, -2, 2, .12);
                        card.capBox.rot = bounded(source.capBox?.rot, -180, 180, 0);
                    }
                    if (cap.k === 'calendar')
                        card.capability.calendarOffset = Math.round(bounded(cap.calendarOffset ?? 0, -120, 120, 0));
                    if (raw.schemaVersion !== 2) {
                        card.capBox.y = i / caps.length;
                        card.capBox.h = 1 / caps.length;
                    }
                }
                else {
                    const extra = new FridgeCard();
                    extra.id = card.id + '_cap_' + i;
                    extra.capability = normalizeCapability(cap);
                    extra.w = card.w;
                    extra.h = card.h;
                    extra.x = Math.min(exports.BOARD_W - extra.w, card.x + 16 * i);
                    extra.y = Math.min(exports.BOARD_H - extra.h, card.y + 16 * i);
                    extra.material = card.material;
                    extra.paper = card.paper;
                    extra.ink = card.ink;
                    extra.rot = card.rot;
                    extra.inDoor = card.inDoor;
                    extra.z = ++state.maxZ;
                    state.cards.push(extra);
                }
            }
            else {
                card.elements.push(legacyElement(cap, card.id, i, caps.length));
                if (cap.k === 'photo' && (cap.label ?? '').length > 0) {
                    const caption = legacyElement({ k: 'text', text: cap.label, fs: 12 }, card.id, i, caps.length);
                    caption.id += '_caption';
                    caption.h = Math.min(0.15, 1 / caps.length);
                    caption.y = (i + 1) / caps.length - caption.h;
                    card.elements.push(caption);
                }
            }
        }
        if (card.capability?.k === 'album') {
            card.shape = 'rect';
            card.frame = false;
        }
        if (card.shape === 'subject' && card.cutout.length === 0)
            card.shape = 'rect';
    }
    return state;
}
exports.normalizeState = normalizeState;
function serializeFaceCards(state) { return JSON.stringify(state.cards.filter((c) => !c.inDoor)); }
exports.serializeFaceCards = serializeFaceCards;
function serializeDoorCards(state) { return JSON.stringify(state.cards.filter((c) => c.inDoor)); }
exports.serializeDoorCards = serializeDoorCards;
function contrastingInk(color) {
    if (!/^#[0-9a-fA-F]{6}$/.test(color))
        return '#FFFFFF';
    const light = .2126 * parseInt(color.slice(1, 3), 16) + .7152 * parseInt(color.slice(3, 5), 16) + .0722 * parseInt(color.slice(5, 7), 16);
    return light >= 145 ? '#262824' : '#FFFFFF';
}
exports.contrastingInk = contrastingInk;
function normalizeCapability(raw) {
    const cap = JSON.parse(JSON.stringify(raw));
    cap.url = undefined;
    cap.field = undefined;
    cap.sourceConfigured = undefined;
    if (raw.k === 'album') {
        const local = (v) => typeof v === 'string' && (v.startsWith('file://') || v.startsWith('memory://')) ? v : '';
        cap.albumCover = local(raw.albumCover);
        cap.albumBackground = local(raw.albumBackground);
        cap.albumId = typeof raw.albumId === 'string' ? raw.albumId.slice(0, 96) : '';
        cap.albumSource = ['local', 'musicbrainz'].includes(raw.albumSource ?? '') ? raw.albumSource : '';
        cap.artist = typeof raw.artist === 'string' ? raw.artist.slice(0, 160) : '';
        cap.albumInset = exports.ALBUM_INSET;
        cap.albumRotationMinutes = [60, 180, 360, 1440].includes(raw.albumRotationMinutes ?? 0) ? raw.albumRotationMinutes : 0;
        cap.albumRotationStart = bounded(raw.albumRotationStart ?? 0, 0, 8640000000000000, 0);
        const ids = [];
        cap.albumItems = (Array.isArray(raw.albumItems) ? raw.albumItems : []).filter((a) => a !== null && a !== undefined && typeof a.id === 'string' && a.id.length > 0 && !!local(a.cover) && !!local(a.background) && !ids.includes(a.id.slice(0, 96)) && (ids.push(a.id.slice(0, 96)) > 0)).slice(0, 12).map((a) => ({ id: a.id.slice(0, 96), cover: local(a.cover), background: local(a.background), title: typeof a.title === 'string' ? a.title.slice(0, 160) : '', artist: typeof a.artist === 'string' ? a.artist.slice(0, 160) : '' }));
    }
    if (raw.k === 'worldclock')
        cap.zone = (0, TimeCapabilities_1.clockZone)(typeof raw.zone === 'string' ? raw.zone : '');
    cap.readingStyle = ['plain', 'surface'].includes(raw.readingStyle ?? '') ? raw.readingStyle : 'auto';
    cap.readingOutside = raw.readingOutside === true;
    cap.readingEdge = ['left', 'right', 'top', 'bottom'].includes(raw.readingEdge ?? '') ? raw.readingEdge : '';
    cap.readingHook = bounded(raw.readingHook ?? .2, 0, 1, .2);
    cap.readingTintKey = typeof raw.readingTintKey === 'string' ? raw.readingTintKey.slice(0, 64) : '';
    cap.readingTint = /^#[0-9a-fA-F]{6}$/.test(raw.readingTint ?? '') ? raw.readingTint : '';
    cap.readingBlend = ['cloud', 'bare', 'badge', 'sticker', 'space', 'tag', 'dock', 'paper', 'feather', 'scrim', 'halo'].includes(raw.readingBlend ?? '') ? raw.readingBlend : 'feather';
    if (raw.k !== 'album')
        cap.readingBlend = ['cloud', 'bare', 'badge', 'sticker', 'space', 'tag', 'dock'].includes(cap.readingBlend ?? '') ? (0, ReadingStylePolicy_1.validReadingStyle)(raw.k, cap.readingBlend) : (0, ReadingStylePolicy_1.defaultReadingStyle)(raw.k);
    cap.parcelPlace = typeof raw.parcelPlace === 'string' ? raw.parcelPlace.slice(0, 80) : '';
    cap.title = typeof raw.title === 'string' ? raw.title.slice(0, 160) : '';
    cap.interval = Math.round(bounded(raw.interval ?? 60, 30, 1440, 60));
    if (raw.k === 'battery')
        cap.percent = bounded(raw.percent ?? -1, -1, 100, -1);
    cap.events = (Array.isArray(raw.events) ? raw.events : []).filter((e) => e && typeof e.title === 'string' && Number.isFinite(e.start) && Number.isFinite(e.end) && e.end >= e.start).slice(0, 256).map((e) => ({ id: String(e.id).slice(0, 96), title: e.title.slice(0, 160), start: e.start, end: e.end, location: typeof e.location === 'string' ? e.location.slice(0, 160) : '', allDay: e.allDay === true }));
    cap.parcels = (Array.isArray(raw.parcels) ? raw.parcels : []).filter((e) => e && typeof e.code === 'string' && e.code.length > 0).slice(0, 64).map((e) => ({ id: String(e.id).slice(0, 96), code: e.code.slice(0, 24), place: typeof e.place === 'string' ? e.place.slice(0, 80) : '', picked: e.picked === true }));
    cap.courses = (Array.isArray(raw.courses) ? raw.courses : []).filter((c) => c && typeof c.name === 'string' && c.name.trim().length > 0 && /^([01]\d|2[0-3]):[0-5]\d$/.test(c.start) && /^([01]\d|2[0-3]):[0-5]\d$/.test(c.end) && c.end > c.start).slice(0, 128).map((c) => ({ id: String(c.id).slice(0, 96), name: c.name.slice(0, 80), room: typeof c.room === 'string' ? c.room.slice(0, 80) : '', day: Math.round(bounded(c.day, 1, 7, 1)), start: c.start, end: c.end, firstWeek: Math.round(bounded(c.firstWeek, 1, 60, 1)), lastWeek: Math.round(bounded(c.lastWeek, c.firstWeek || 1, 60, 16)), parity: [0, 1, 2].includes(c.parity) ? c.parity : 0 }));
    if (raw.k === 'timetable') {
        cap.timetableMode = raw.timetableMode === 'day' ? 'day' : 'next';
        cap.skipHolidays = raw.skipHolidays !== false;
        cap.holidayDates = (Array.isArray(raw.holidayDates) ? raw.holidayDates : []).filter((d) => d && (0, HolidayCalendar_1.validDay)(d.date)).slice(0, 512).map((d) => ({ date: d.date, name: typeof d.name === 'string' ? d.name.slice(0, 60) : '校历假期' }));
        cap.teachingDays = (Array.isArray(raw.teachingDays) ? raw.teachingDays : []).filter((d) => d && (0, HolidayCalendar_1.validDay)(d.date) && (d.sourceDate === '' || (0, HolidayCalendar_1.validDay)(d.sourceDate))).slice(-512);
        cap.courseChanges = (Array.isArray(raw.courseChanges) ? raw.courseChanges : []).filter((d) => d && typeof d.id === 'string' && cap.courses.some((c) => c.id === d.courseId) && (0, HolidayCalendar_1.validDay)(d.date) && (d.targetDate === '' || ((0, HolidayCalendar_1.validDay)(d.targetDate) && /^([01]\d|2[0-3]):[0-5]\d$/.test(d.start) && /^([01]\d|2[0-3]):[0-5]\d$/.test(d.end) && d.end > d.start))).slice(-256).map((d) => ({ id: d.id.slice(0, 96), courseId: d.courseId, date: d.date, targetDate: d.targetDate, start: d.start ?? '', end: d.end ?? '', room: typeof d.room === 'string' ? d.room.slice(0, 80) : '' }));
    }
    return cap;
}
exports.normalizeCapability = normalizeCapability;

},
"ReadingStylePolicy":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.preferredReadingStyle = exports.validReadingStyle = exports.defaultReadingStyle = exports.readingStyles = exports.COMPOSITION_KEYS = void 0;
exports.COMPOSITION_KEYS = ['cloud', 'bare', 'badge', 'sticker', 'tag'];
function readingStyles(kind) {
    if (kind === 'album')
        return [];
    return kind === 'battery' ? ['badge', 'cloud', 'bare', 'tag', 'sticker'] : ['cloud', 'bare', 'tag', 'sticker'];
}
exports.readingStyles = readingStyles;
function defaultReadingStyle(kind) {
    if (kind === 'battery')
        return 'badge';
    if (kind === 'agenda' || kind === 'timetable' || kind === 'countdown' || kind === 'anniversary' || kind.endsWith('progress'))
        return 'tag';
    return kind === 'clock' ? 'bare' : 'sticker';
}
exports.defaultReadingStyle = defaultReadingStyle;
function validReadingStyle(kind, style) {
    const migrated = style === 'dock' ? 'tag' : style === 'space' ? 'sticker' : style;
    return readingStyles(kind).includes(migrated) ? migrated : defaultReadingStyle(kind);
}
exports.validReadingStyle = validReadingStyle;
/** Newly chosen capabilities use cloud; legacy defaults stay stable during migration. */
function preferredReadingStyle(kind) { return kind === 'battery' ? 'badge' : kind === 'album' ? '' : 'cloud'; }
exports.preferredReadingStyle = preferredReadingStyle;

},
"SceneScheduleSchema":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sceneClock = exports.normalizeSceneRules = exports.normalizeSceneLayouts = exports.validSceneDate = exports.sceneDay = exports.SceneRule = exports.SavedSceneLayout = exports.ScenePlacement = void 0;
/** Local wall-clock rules. Geometry references artwork; it never duplicates image assets. */
class ScenePlacement {
    constructor() {
        this.id = '';
        this.x = 0;
        this.y = 0;
        this.w = 180;
        this.h = 180;
        this.rot = 0;
        this.z = 1;
    }
}
exports.ScenePlacement = ScenePlacement;
class SavedSceneLayout {
    constructor() {
        this.id = '';
        this.name = '';
        this.placements = [];
    }
}
exports.SavedSceneLayout = SavedSceneLayout;
class SceneRule {
    constructor() {
        this.id = '';
        this.name = '';
        this.enabled = true;
        this.kind = 'layout';
        this.targetId = '';
        this.repeat = 'daily';
        this.date = '';
        this.weekdays = [0, 1, 2, 3, 4, 5, 6];
        this.start = 1200;
        this.end = 1380;
        this.untilDismissed = true;
        this.createdAt = 0;
        this.dismissed = '';
    }
}
exports.SceneRule = SceneRule;
function sceneDay(date) { return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0'); }
exports.sceneDay = sceneDay;
function validSceneDate(value) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(value))
        return false;
    const parts = value.split('-').map(Number), date = new Date(parts[0], parts[1] - 1, parts[2]);
    return sceneDay(date) === value;
}
exports.validSceneDate = validSceneDate;
function number(value, min, max, fallback) { return Number.isFinite(value) ? Math.max(min, Math.min(max, value)) : fallback; }
function normalizeSceneLayouts(raw) {
    const out = [];
    for (const source of (Array.isArray(raw) ? raw : []).slice(0, 8)) {
        if (!source || typeof source.id !== 'string' || !source.id || out.some(s => s.id === source.id))
            continue;
        const next = new SavedSceneLayout();
        next.id = source.id.slice(0, 96);
        next.name = (typeof source.name === 'string' ? source.name : '布局').slice(0, 30);
        for (const p of (Array.isArray(source.placements) ? source.placements : []).slice(0, 32)) {
            if (!p || typeof p.id !== 'string' || next.placements.some(s => s.id === p.id))
                continue;
            const item = new ScenePlacement();
            item.id = p.id.slice(0, 96);
            item.x = number(p.x, -840, 1184, 0);
            item.y = number(p.y, -840, 1310, 0);
            item.w = number(p.w, 16, 320, 180);
            item.h = number(p.h, 16, 420, 180);
            item.rot = number(p.rot, -180, 180, 0);
            item.z = number(p.z, 0, Number.MAX_SAFE_INTEGER, 1);
            next.placements.push(item);
        }
        out.push(next);
    }
    return out;
}
exports.normalizeSceneLayouts = normalizeSceneLayouts;
function normalizeSceneRules(raw) {
    const out = [];
    for (const source of (Array.isArray(raw) ? raw : []).slice(0, 12)) {
        if (!source || typeof source.id !== 'string' || !source.id || out.some(s => s.id === source.id) || !['layout', 'canvas', 'focus'].includes(source.kind))
            continue;
        const rule = new SceneRule();
        rule.id = source.id.slice(0, 96);
        rule.name = (typeof source.name === 'string' ? source.name : '定时场景').slice(0, 30);
        rule.enabled = source.enabled !== false;
        rule.kind = source.kind;
        rule.targetId = (typeof source.targetId === 'string' ? source.targetId : '').slice(0, 96);
        rule.repeat = source.repeat === 'once' ? 'once' : 'daily';
        rule.date = typeof source.date === 'string' && validSceneDate(source.date) ? source.date : '';
        if (rule.repeat === 'once' && !rule.date)
            rule.enabled = false;
        rule.weekdays = Array.from(new Set((Array.isArray(source.weekdays) ? source.weekdays : rule.weekdays).filter((n) => Number.isInteger(n) && n >= 0 && n < 7)));
        rule.start = Math.round(number(source.start, 0, 1439, 1200));
        rule.end = Math.round(number(source.end, 0, 1439, 1380));
        rule.untilDismissed = source.untilDismissed !== false;
        rule.createdAt = number(source.createdAt, 0, Number.MAX_SAFE_INTEGER, 0);
        rule.dismissed = typeof source.dismissed === 'string' ? source.dismissed.slice(0, 24) : '';
        out.push(rule);
    }
    return out;
}
exports.normalizeSceneRules = normalizeSceneRules;
function sceneClock(minute) { return String(Math.floor(minute / 60)).padStart(2, '0') + ':' + String(minute % 60).padStart(2, '0'); }
exports.sceneClock = sceneClock;

},
"TimeCapabilities":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.lunarReading = exports.LunarReading = exports.nextCityBoundary = exports.nextCityMidnight = exports.cityReading = exports.CityReading = exports.clockOffset = exports.clockCity = exports.clockZone = exports.CLOCK_CITIES = void 0;
exports.CLOCK_CITIES = [
    { value: '北京', zone: 'Asia/Shanghai' }, { value: '东京', zone: 'Asia/Tokyo' },
    { value: '首尔', zone: 'Asia/Seoul' }, { value: '新加坡', zone: 'Asia/Singapore' },
    { value: '曼谷', zone: 'Asia/Bangkok' }, { value: '迪拜', zone: 'Asia/Dubai' },
    { value: '新德里', zone: 'Asia/Kolkata' }, { value: '加德满都', zone: 'Asia/Kathmandu' },
    { value: '伦敦', zone: 'Europe/London' }, { value: '巴黎', zone: 'Europe/Paris' },
    { value: '柏林', zone: 'Europe/Berlin' }, { value: '纽约', zone: 'America/New_York' },
    { value: '洛杉矶', zone: 'America/Los_Angeles' }, { value: '温哥华', zone: 'America/Vancouver' },
    { value: '悉尼', zone: 'Australia/Sydney' }, { value: '阿德莱德', zone: 'Australia/Adelaide' },
    { value: '奥克兰', zone: 'Pacific/Auckland' }, { value: '檀香山', zone: 'Pacific/Honolulu' }
];
function clockZone(zone = '') { return exports.CLOCK_CITIES.some((city) => city.zone === zone) ? zone : 'Asia/Shanghai'; }
exports.clockZone = clockZone;
function clockCity(zone = '') { return exports.CLOCK_CITIES.find((city) => city.zone === clockZone(zone)).value; }
exports.clockCity = clockCity;
const formatters = new Map();
const offsets = new Map();
function formatter(zone) {
    let value = formatters.get(zone);
    if (!value) {
        value = new Intl.DateTimeFormat('en-US', { timeZone: zone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' });
        formatters.set(zone, value);
    }
    return value;
}
/** TextClock uses the opposite sign to UTC offsets, including supported half/quarter-hour zones. */
function clockOffset(zone, now) {
    zone = clockZone(zone);
    const minute = Math.floor(now / 60000), cached = offsets.get(zone);
    if (cached?.minute === minute)
        return cached.offset;
    const parts = formatter(zone).formatToParts(new Date(now));
    const field = (key) => Number(parts.find((part) => part.type === key)?.value ?? 0);
    const offset = -(Date.UTC(field('year'), field('month') - 1, field('day'), field('hour'), field('minute'), field('second')) - Math.floor(now / 1000) * 1000) / 3600000 || 0;
    offsets.set(zone, { minute: minute, offset: offset });
    return offset;
}
exports.clockOffset = clockOffset;
class CityReading {
    constructor() {
        this.city = '';
        this.date = '';
        this.difference = '';
    }
}
exports.CityReading = CityReading;
function cityReading(zone, now) {
    const result = new CityReading(), offset = clockOffset(zone, now), date = new Date(now - offset * 3600000), local = new Date(now);
    const localOffset = local.getTimezoneOffset() / 60, difference = localOffset - offset;
    result.city = clockCity(zone);
    result.date = (date.getUTCMonth() + 1) + '月' + date.getUTCDate() + '日 · ' + ['周日', '周一', '周二', '周三', '周四', '周五', '周六'][date.getUTCDay()];
    result.difference = Math.abs(difference) < .01 ? '与本地同一时区' : (difference > 0 ? '比本地快 ' : '比本地慢 ') + Math.abs(difference) + ' 小时';
    return result;
}
exports.cityReading = cityReading;
function nextCityMidnight(zone, now) {
    const offset = clockOffset(zone, now), date = new Date(now - offset * 3600000);
    const midnight = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + 1);
    let result = midnight + offset * 3600000;
    for (let i = 0; i < 3; i++)
        result = midnight + clockOffset(zone, result) * 3600000;
    return result;
}
exports.nextCityMidnight = nextCityMidnight;
/** Prioritize a nearby DST transition; the FormKit caller still honors its 5-minute quota. */
function nextCityBoundary(zone, now) {
    let result = nextCityMidnight(zone, now), end = now + 30 * 60000;
    const offset = clockOffset(zone, now);
    if (clockOffset(zone, end) !== offset) {
        let lo = Math.floor(now / 60000), hi = Math.ceil(end / 60000);
        while (hi - lo > 1) {
            const mid = Math.floor((lo + hi) / 2);
            if (clockOffset(zone, mid * 60000) === offset)
                lo = mid;
            else
                hi = mid;
        }
        result = Math.min(result, hi * 60000);
    }
    return result;
}
exports.nextCityBoundary = nextCityBoundary;
class LunarReading {
    constructor() {
        this.date = '';
        this.year = '';
    }
}
exports.LunarReading = LunarReading;
let lunarFormatter = undefined;
let lunarKey = '', lunarValue = new LunarReading();
function lunarReading(now) {
    const date = new Date(now), key = date.getFullYear() + ':' + date.getMonth() + ':' + date.getDate() + ':' + date.getTimezoneOffset();
    if (key === lunarKey)
        return lunarValue;
    lunarFormatter = new Intl.DateTimeFormat('zh-CN-u-ca-chinese', { year: 'numeric', month: 'long', day: 'numeric' });
    const parts = lunarFormatter.formatToParts(date), day = Number(parts.find((part) => part.type === 'day')?.value ?? 0);
    const names = ['', '初一', '初二', '初三', '初四', '初五', '初六', '初七', '初八', '初九', '初十', '十一', '十二', '十三', '十四', '十五', '十六', '十七', '十八', '十九', '二十', '廿一', '廿二', '廿三', '廿四', '廿五', '廿六', '廿七', '廿八', '廿九', '三十'];
    const result = new LunarReading();
    result.date = (parts.find((part) => part.type === 'month')?.value ?? '') + ' ' + (names[day] ?? '');
    result.year = parts.filter((part) => String(part.type) === 'yearName').map((part) => part.value).join('') + '年';
    lunarKey = key;
    lunarValue = result;
    return result;
}
exports.lunarReading = lunarReading;

},
"HolidayCalendar":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.holidayFileDates = exports.daysBetween = exports.holidayMarker = exports.holidayName = exports.missingHolidayYears = exports.holidayDataLabel = exports.holidayKnown = exports.HOLIDAY_DATA_REVISION = exports.HOLIDAY_YEARS = exports.validDay = exports.dateKey = exports.HOLIDAY_PERIODS = void 0;
exports.HOLIDAY_PERIODS = [
    { start: '2025-01-01', end: '2025-01-01', name: '元旦' },
    { start: '2025-01-28', end: '2025-02-04', name: '春节' },
    { start: '2025-04-04', end: '2025-04-06', name: '清明节' },
    { start: '2025-05-01', end: '2025-05-05', name: '劳动节' },
    { start: '2025-05-31', end: '2025-06-02', name: '端午节' },
    { start: '2025-10-01', end: '2025-10-08', name: '国庆／中秋' },
    { start: '2026-01-01', end: '2026-01-03', name: '元旦' },
    { start: '2026-02-15', end: '2026-02-23', name: '春节' },
    { start: '2026-04-04', end: '2026-04-06', name: '清明节' },
    { start: '2026-05-01', end: '2026-05-05', name: '劳动节' },
    { start: '2026-06-19', end: '2026-06-21', name: '端午节' },
    { start: '2026-09-25', end: '2026-09-27', name: '中秋节' },
    { start: '2026-10-01', end: '2026-10-07', name: '国庆节' }
];
const WORK_DAYS = ['2025-01-26', '2025-02-08', '2025-04-27', '2025-09-28', '2025-10-11',
    '2026-01-04', '2026-02-14', '2026-02-28', '2026-05-09', '2026-09-20', '2026-10-10'];
function dateKey(date) { return date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + ('0' + date.getDate()).slice(-2); }
exports.dateKey = dateKey;
function validDay(value) {
    if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value))
        return false;
    const date = new Date(value + 'T12:00:00');
    return Number.isFinite(date.getTime()) && dateKey(date) === value;
}
exports.validDay = validDay;
exports.HOLIDAY_YEARS = Array.from(new Set(exports.HOLIDAY_PERIODS.map((p) => Number(p.start.slice(0, 4))))).sort((a, b) => a - b);
exports.HOLIDAY_DATA_REVISION = 'CN-2026-official-r1';
function holidayKnown(year) { return exports.HOLIDAY_YEARS.includes(year); }
exports.holidayKnown = holidayKnown;
function holidayDataLabel() { return exports.HOLIDAY_YEARS.join('、') + ' 年官方安排 · 随应用版本更新'; }
exports.holidayDataLabel = holidayDataLabel;
/** Validate the whole semester, including its next calendar year. Never extrapolate. */
function missingHolidayYears(semester, weeks) {
    if (!validDay(semester))
        return holidayKnown(new Date().getFullYear()) ? [] : [new Date().getFullYear()];
    const start = new Date(semester + 'T12:00:00'), end = new Date(start.getTime());
    end.setDate(end.getDate() + Math.max(1, Math.min(60, Number.isFinite(weeks) ? Math.round(weeks) : 1)) * 7 - 1);
    const missing = [];
    for (let year = start.getFullYear(); year <= end.getFullYear(); year++)
        if (!holidayKnown(year))
            missing.push(year);
    return missing;
}
exports.missingHolidayYears = missingHolidayYears;
function holidayName(date) {
    const key = dateKey(date), period = exports.HOLIDAY_PERIODS.find((p) => key >= p.start && key <= p.end);
    return period?.name ?? '';
}
exports.holidayName = holidayName;
function holidayMarker(date) { return holidayName(date) ? '休' : WORK_DAYS.includes(dateKey(date)) ? '班' : ''; }
exports.holidayMarker = holidayMarker;
function daysBetween(start, end) {
    if (!validDay(start) || !validDay(end) || end < start)
        throw new Error('请选择有效的起止日期');
    const out = [], date = new Date(start + 'T12:00:00');
    while (dateKey(date) <= end && out.length <= 120) {
        out.push(dateKey(date));
        date.setDate(date.getDate() + 1);
    }
    if (out.length > 120)
        throw new Error('单次最多设置 120 天');
    return out;
}
exports.daysBetween = daysBetween;
/** All-day, explicit-date ICS only; recurrence is rejected rather than silently misread. */
function holidayFileDates(text) {
    if (text.length > 1048576 || !text.includes('BEGIN:VCALENDAR'))
        throw new Error('请选择有效的节假日日历 .ics 文件');
    const blocks = text.replace(/\r?\n[ \t]/g, '').match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/g) ?? [], out = [];
    for (const block of blocks) {
        if (/\n(?:RRULE|RDATE|EXDATE|RECURRENCE-ID)[;:]/.test(block))
            throw new Error('请导出含明确日期的假期日历，不支持循环规则');
        const start = block.match(/(?:^|\n)DTSTART(?:;VALUE=DATE)?:([0-9]{8})\r?\n/), end = block.match(/(?:^|\n)DTEND(?:;VALUE=DATE)?:([0-9]{8})\r?\n/);
        if (!start)
            throw new Error('假期日历须为全天事件，普通日程请从日程能力导入');
        const key = (v) => v.slice(0, 4) + '-' + v.slice(4, 6) + '-' + v.slice(6);
        const first = key(start[1]);
        let last = first;
        if (end) {
            const exclusive = key(end[1]);
            if (!validDay(exclusive) || exclusive <= first)
                throw new Error('假期结束日期无效');
            const date = new Date(exclusive + 'T12:00:00');
            date.setDate(date.getDate() - 1);
            last = dateKey(date);
        }
        const name = (block.match(/(?:^|\n)SUMMARY(?:;[^:]*)?:([^\r\n]*)/)?.[1] ?? '校历假期').replace(/\\n/g, ' ').replace(/\\([,;\\])/g, '$1').slice(0, 60);
        for (const date of daysBetween(first, last))
            if (!out.some((v) => v.date === date))
                out.push({ date: date, name: name });
        if (out.length > 512)
            throw new Error('假期日历超过 512 天');
    }
    if (!out.length)
        throw new Error('文件中没有明确的全天假期');
    return out;
}
exports.holidayFileDates = holidayFileDates;

},
"CanvasCapacity":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.canvasCapacityHint = exports.assertCanvasCapacity = exports.CANVAS_CARD_LIMIT = exports.CANVAS_CARD_TARGET = void 0;
/** Per-canvas policy. Existing stored works are never truncated by this limit. */
exports.CANVAS_CARD_TARGET = 12;
exports.CANVAS_CARD_LIMIT = 16;
function assertCanvasCapacity(current, incoming = 1) {
    if (!Number.isInteger(current) || !Number.isInteger(incoming) || current < 0 || incoming < 0) {
        throw new Error('卡片数量无效');
    }
    if (current + incoming > exports.CANVAS_CARD_LIMIT) {
        throw new Error('每张画布最多 16 张卡片，请新建画布后添加');
    }
}
exports.assertCanvasCapacity = assertCanvasCapacity;
function canvasCapacityHint(count) {
    if (count < exports.CANVAS_CARD_TARGET)
        return '';
    return count >= exports.CANVAS_CARD_LIMIT ? '已达上限，可新建画布继续创作' : '建议将新作品放到另一张画布';
}
exports.canvasCapacityHint = canvasCapacityHint;

},
"AlbumLayout":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.albumInfoGeometry = exports.isSquareAlbumCover = exports.albumAnchors = exports.albumCoverRadius = exports.albumCoverSize = void 0;
const CardSchema_1 = require("./CardSchema");
/** Stable, square cover centred in every card aspect ratio; no runtime animation. */
function albumCoverSize(width, height, inset = CardSchema_1.ALBUM_INSET) { return Math.max(0, Math.min(width, height) * (1 - 2 * Math.max(0, Math.min(20, inset)) / 100)); }
exports.albumCoverSize = albumCoverSize;
/** Original subtle artwork corner; clamp for very small artwork. */
function albumCoverRadius(width, height, inset = CardSchema_1.ALBUM_INSET) { return Math.min(CardSchema_1.ALBUM_CORNER_RADIUS, albumCoverSize(width, height, inset) / 2); }
exports.albumCoverRadius = albumCoverRadius;
function albumAnchors(palette) {
    const positions = [[.18, .24], [.82, .32], [.48, .84]];
    return palette.slice(0, 3).map((color, i) => ({ color: color, x: positions[i][0], y: positions[i][1], weight: 1 }));
}
exports.albumAnchors = albumAnchors;
/** Album artwork is square; reject other ratios before decoding or creating assets. */
function isSquareAlbumCover(width, height) { return Number.isInteger(width) && width > 0 && width === height; }
exports.isSquareAlbumCover = isSquareAlbumCover;
function albumInfoGeometry(width, height, style) {
    const w = Math.max(0, width), h = Math.max(0, height), pad = Math.min(16, w * .075, h * .075);
    if (style === 'row') {
        const cover = Math.max(0, Math.min(h - 2 * pad, w * .43));
        return { coverX: pad, coverY: (h - cover) / 2, coverSize: cover, textX: pad + cover + 12, textY: h * .36, textWidth: Math.max(0, w - 2 * pad - cover - 12), titleSize: Math.min(17, w * .072), artistSize: Math.min(14, w * .06) };
    }
    const large = style === 'portrait', size = Math.max(0, Math.min(w - 2 * pad, h * (large ? .66 : .49)));
    return { coverX: pad, coverY: pad, coverSize: size, textX: pad, textY: pad + size + (large ? 10 : 16), textWidth: Math.max(0, w - 2 * pad), titleSize: Math.min(18, w * .085), artistSize: Math.min(15, w * .068) };
}
exports.albumInfoGeometry = albumInfoGeometry;

},
"AlbumRotation":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.selectAlbum = exports.nextAlbumBoundary = exports.activeAlbum = exports.albumLibrary = void 0;
/** Elapsed wall time, not timer counts: app, widget and reopened app agree. */
function albumLibrary(cap) {
    const items = (cap.albumItems ?? []).slice();
    if (cap.albumCover && !items.some(a => a.cover === cap.albumCover))
        items.unshift({ id: cap.albumId || cap.albumCover, cover: cap.albumCover, background: cap.albumBackground ?? '', title: cap.title ?? '', artist: cap.artist ?? '' });
    return items.slice(0, 12);
}
exports.albumLibrary = albumLibrary;
function activeAlbum(cap, now = Date.now()) {
    const items = albumLibrary(cap);
    if (!items.length)
        return { id: '', cover: '', background: '', title: '', artist: '' };
    const base = Math.max(0, items.findIndex(a => a.id === cap.albumId));
    const period = (cap.albumRotationMinutes ?? 0) * 60000, start = cap.albumRotationStart ?? 0;
    const steps = period > 0 && start > 0 ? Math.floor(Math.max(0, now - start) / period) : 0;
    return items[(base + steps) % items.length];
}
exports.activeAlbum = activeAlbum;
function nextAlbumBoundary(cap, now) {
    const period = (cap.albumRotationMinutes ?? 0) * 60000, start = cap.albumRotationStart ?? 0;
    return period > 0 && start > 0 && albumLibrary(cap).length > 1 ? start + (Math.floor(Math.max(0, now - start) / period) + 1) * period : Infinity;
}
exports.nextAlbumBoundary = nextAlbumBoundary;
function selectAlbum(cap, album, now = Date.now()) {
    const next = JSON.parse(JSON.stringify(cap));
    next.albumItems = albumLibrary(cap);
    next.albumId = album.id;
    next.albumCover = album.cover;
    next.albumBackground = album.background;
    next.title = album.title;
    next.artist = album.artist;
    next.albumRotationStart = now;
    return next;
}
exports.selectAlbum = selectAlbum;

},
"CardDepth":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cardEdgeColor = exports.cardDepthScale = void 0;
/** All physical relief scales with artwork, including smaller desktop hosts. */
function cardDepthScale(scale) { return Number.isFinite(scale) ? Math.max(0, scale) : 1; }
exports.cardDepthScale = cardDepthScale;
function cardEdgeColor(color, photoSubject) {
    const source = photoSubject ? '#FFFFFF' : color;
    if (!/^#[0-9a-fA-F]{6}$/.test(source))
        return '#D2CEC5';
    // Warm neutral substrate; preserve each card's hue instead of a generic grey slab.
    const channels = [0, 1, 2].map((i) => Math.round(parseInt(source.slice(1 + i * 2, 3 + i * 2), 16) * .78 + [35, 33, 29][i]));
    return '#' + channels.map((n) => Math.max(0, Math.min(255, n)).toString(16).padStart(2, '0')).join('');
}
exports.cardEdgeColor = cardEdgeColor;

},
"ContourPath":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.contourPath = void 0;
/** Round only raster-scale bends, within 0.12% of the source box. Long deliberate corners stay pinned. */
function contourPath(loops, width, height, factor) {
    const commands = [], inset = (1 - factor) / 2;
    // SVG's native parser need not scan 15 decimal digits for subpixel vertices.
    const coordinate = (value) => String(Math.round(value * 100) / 100);
    for (const loop of loops) {
        if (loop.length < 3)
            continue;
        const before = [], after = [];
        for (let i = 0; i < loop.length; i++) {
            const p = loop[i], a = loop[(i + loop.length - 1) % loop.length], b = loop[(i + 1) % loop.length];
            const u = Math.hypot(p.x - a.x, p.y - a.y), v = Math.hypot(b.x - p.x, b.y - p.y);
            const radius = u > .02 && v > .02 ? 0 : Math.min(.0012, u * .2, v * .2);
            before.push({ x: p.x + (a.x - p.x) * radius / Math.max(u, .000001), y: p.y + (a.y - p.y) * radius / Math.max(u, .000001) });
            after.push({ x: p.x + (b.x - p.x) * radius / Math.max(v, .000001), y: p.y + (b.y - p.y) * radius / Math.max(v, .000001) });
        }
        commands.push('M' + coordinate((inset + before[0].x * factor) * width) + ',' + coordinate((inset + before[0].y * factor) * height));
        for (let i = 0; i < loop.length; i++) {
            const p = loop[i], q = after[i], next = before[(i + 1) % loop.length];
            if (q.x !== p.x || q.y !== p.y)
                commands.push('Q' + coordinate((inset + p.x * factor) * width) + ',' + coordinate((inset + p.y * factor) * height) + ' ' + coordinate((inset + q.x * factor) * width) + ',' + coordinate((inset + q.y * factor) * height));
            commands.push('L' + coordinate((inset + next.x * factor) * width) + ',' + coordinate((inset + next.y * factor) * height));
        }
        commands.push('Z');
    }
    return commands.join(' ');
}
exports.contourPath = contourPath;

},
"CloudReadingGeometry":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cloudReadingPath = exports.CLOUD_READING_FRINGE = exports.CLOUD_READING_OUTSET = exports.CLOUD_READING_PADDING = void 0;
/** Decoration stays outside the existing reading gutter; resizing never cuts into text. */
exports.CLOUD_READING_PADDING = 8;
exports.CLOUD_READING_OUTSET = 16;
exports.CLOUD_READING_FRINGE = exports.CLOUD_READING_OUTSET * 2 + 4;
/** Broad, asymmetric shoulders replace repeated scallops. Aspect-dependent curvature
 * varies continuously: no random seed, lobe-count switch or per-frame bitmap work. */
function cloudReadingPath(w, h, scale) {
    if (!Number.isFinite(w) || !Number.isFinite(h) || !Number.isFinite(scale) || w <= 0 || h <= 0 || scale <= 0)
        return '';
    const W = w + 2 * exports.CLOUD_READING_OUTSET * scale, H = h + 2 * exports.CLOUD_READING_OUTSET * scale;
    const p = Math.min(10 * scale, Math.min(W, H) * .1), l = p, r = W - p, t = p, b = H - p;
    const radius = Math.min(24 * scale, Math.min(W, H) * .27);
    const rx = radius * (1 + .12 * (w - h) / (w + h)), ry = radius * (1 - .12 * (w - h) / (w + h));
    const spanX = r - l - 2 * rx, spanY = b - t - 2 * ry;
    const ax = Math.min(p * .65, spanX * .09), ay = Math.min(p * .58, spanY * .09);
    const x0 = l + rx, x1 = r - rx, y0 = t + ry, y1 = b - ry;
    const xm = x0 + spanX * .57, ym = y0 + spanY * .43;
    // Tangents are shared at every join, including the softened corner shoulders.
    return `M ${x0} ${t}
 C ${x0 + spanX * .16} ${t} ${xm - spanX * .15} ${t - ax} ${xm} ${t - ax}
 C ${xm + spanX * .15} ${t - ax} ${x1 - spanX * .13} ${t} ${x1} ${t}
 C ${x1 + rx * .62} ${t} ${r} ${y0 - ry * .58} ${r} ${y0}
 C ${r} ${y0 + spanY * .13} ${r + ay} ${ym - spanY * .12} ${r + ay} ${ym}
 C ${r + ay} ${ym + spanY * .2} ${r} ${y1 - spanY * .16} ${r} ${y1}
 C ${r} ${y1 + ry * .6} ${x1 + rx * .58} ${b} ${x1} ${b}
 C ${x1 - spanX * .18} ${b} ${xm + spanX * .14} ${b + ax * .7} ${xm} ${b + ax * .7}
 C ${xm - spanX * .2} ${b + ax * .7} ${x0 + spanX * .13} ${b} ${x0} ${b}
 C ${x0 - rx * .62} ${b} ${l} ${y1 + ry * .56} ${l} ${y1}
 C ${l} ${y1 - spanY * .2} ${l - ay * .8} ${ym + spanY * .17} ${l - ay * .8} ${ym}
 C ${l - ay * .8} ${ym - spanY * .12} ${l} ${y0 + spanY * .14} ${l} ${y0}
 C ${l} ${y0 - ry * .6} ${x0 - rx * .56} ${t} ${x0} ${t} Z`;
}
exports.cloudReadingPath = cloudReadingPath;

}};const cache={};function load(name){if(cache[name])return cache[name].exports;if(!modules[name])throw Error("Unknown shared model "+name);const module={exports:{}};cache[name]=module;modules[name](s=>load(s.replace(/^\.\//,"")),module,module.exports);return module.exports;}global.FridgeCore={load,sourceFingerprint:"a1fd3d905196b2fa8fba0708ba9f47a3b2eca03517278baaac8f7c14d1297abf"};})(globalThis);
