const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ts=require('/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript');
const root=path.resolve(__dirname,'../entry/src/main/ets/model'),cache=new Map();
function load(name){const file=path.resolve(root,name+'.ets');if(cache.has(file))return cache.get(file).exports;const mod={exports:{}};cache.set(file,mod);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInThisContext('(function(require,module,exports){'+code+'\n})',{filename:file})(s=>s==='@kit.ArkTS'?{taskpool:{}}:load(path.relative(root,path.resolve(path.dirname(file),s))),mod,mod.exports);return mod.exports;}
const s=load('CardSchema'),c=load('CapabilityCatalog'),p=load('CapabilityPresentation'),g=load('CanvasLayout'),m=load('CapabilityMetrics'),intake=load('ParcelIntake'),actions=load('WidgetActions'),hit=load('WidgetHitTest'),templates=load('TemplatePackage');
assert.deepEqual(c.CAPABILITY_CATALOG.map(x=>x.key).sort(),s.CAPABILITIES.slice().sort(),'every shipped capability has a source/purpose/detail contract');
for(const cap of c.CAPABILITY_CATALOG){assert.ok(cap.source&&cap.summary&&cap.detail);assert.ok(c.CAPABILITY_GROUPS.includes(cap.group));const min=m.capabilityMinimum({k:cap.key},true);assert.ok(min.w>=64&&min.h>=36);}
const parcels=Array.from({length:5},(_,i)=>({id:'parcel'+i,code:'2-'+i+'234',place:'东门菜鸟驿站',picked:false}));
for(const [height,count] of [[82,1],[120,1],[136,2],[170,3],[300,3]]){
 const view=p.summaryPresentation({k:'parcel',parcels},height,Date.now());assert.equal(view.parcels.length,count);assert.equal(view.remaining,5-count);assert.ok(16+8+(count*40)+(count-1)*8<=height,'header and every row fit without text compression');
}
assert.ok(m.capabilityMinimum({k:'countdown',date:'9999-12-31'},true).w>=100,'long countdowns gain width instead of unreadable type');
const now=new Date('2026-10-04T09:00:00').getTime();const events=[{id:'a',title:'设计评审',location:'会议室203',start:now+3600000,end:now+7200000},{id:'b',title:'买菜',start:now+10800000,end:now+14400000},{id:'c',title:'过期',start:0,end:1}];assert.equal(p.summaryPresentation({k:'agenda',events},136,now).events.length,2);assert.equal(p.summaryPresentation({k:'agenda',events},82,now).events[0].id,'a');
assert.equal(p.summaryPresentation({k:'agenda',events:events.concat(Array.from({length:7},(_,i)=>({id:'next'+i,title:'后续',start:now+(i+5)*3600000,end:now+(i+6)*3600000})))},82,now).remaining,8,'remaining count includes the whole upcoming list');
assert.equal(p.readingSurface({k:'parcel'},true,false),true);assert.equal(p.readingSurface({k:'parcel',readingStyle:'plain'},true,false),false);assert.equal(p.readingSurface({k:'parcel',readingStyle:'plain'},false,true),true,'overlap fallback remains readable');
for(const shape of ['rect','round','pill','blob','subject']){
 const card=new s.FridgeCard();card.id=shape;card.w=240;card.h=280;card.shape=shape;card.capability={k:'parcel',readingStyle:'surface'};card.outline=[[{x:.1,y:.1},{x:.9,y:.1},{x:.9,y:.9},{x:.1,y:.9}]];
 assert.ok(g.ensureCapabilitySize(card));const safe=g.safeContentBox(card);for(const anchor of ['top','center','bottom']){const box=g.capabilityPreset(card,anchor);assert.ok(box.x>=safe.x-.001&&box.y>=safe.y-.001&&box.x+box.w<=safe.x+safe.w+.001&&box.y+box.h<=safe.y+safe.h+.001);assert.ok(m.capabilityFits(card.capability,box.w*card.w-16,box.h*card.h-16));}
}
const notices=intake.parsePickupNotice('登录验证码123456；请到东门菜鸟驿站，取件码【２－１２３４】。请至西门丰巢快递柜，取件码 9-4567。');assert.equal(notices.length,2);assert.equal(notices[0].place,'东门菜鸟驿站');assert.equal(notices[1].place,'西门丰巢快递柜');assert.equal(notices[0].code,'2-1234');
for(const raw of ['验证码123456，订单号888999000','取件码：13812345678','取件码：123456789012345678','取件码：abcdef'])assert.equal(intake.parsePickupNotice(raw).length,0);
assert.equal(intake.parsePickupNotice('取件码 2-1234 please collect')[0].code,'2-1234');
const missing=intake.parsePickupNotice('取件码:88-99');assert.equal(missing[0].place,'');let merged=intake.mergePickupParcels([],missing,'学校驿站',now);assert.equal(merged[0].place,'学校驿站');assert.equal(intake.mergePickupParcels(merged,missing,'学校驿站',now).length,1);merged[0].picked=true;assert.equal(intake.mergePickupParcels(merged,missing,'学校驿站',now).length,2,'a code can be reused after pickup');
assert.throws(()=>intake.mergePickupParcels(Array.from({length:64},(_,i)=>({id:''+i,code:''+i,place:'old',picked:false})),missing,'new',now),/记录已满/);
const cal=new s.FridgeCard();cal.id='calendar';cal.w=260;cal.h=320;cal.x=30;cal.y=50;cal.rot=27;cal.capability={k:'calendar'};cal.capBox=g.capabilityPreset(cal,'center');const scale=1.4,width=344*scale,height=344*scale;
const rects=actions.widgetActionRects(cal,scale,now);assert.equal(rects.length,2);for(const rect of rects){assert.equal(rect.w*scale,44);assert.equal(rect.h*scale,44);const at=hit.widgetCanvasPoint(cal,(rect.x+rect.w/2)*scale,(rect.y+rect.h/2)*scale,width,height);const result=hit.widgetHit([cal],at.x,at.y,width,height,now);assert.equal(result.id,cal.id);assert.equal(result.operation,rect.operation);}
cal.w=140;cal.h=100;cal.capBox=g.safeContentBox(cal);assert.equal(actions.widgetActionRects(cal,scale,now).length,0,'compact calendar has no invisible/tiny month controls');
const state=s.defaultState();state.cards=[new s.FridgeCard()];state.cards[0].id='private';state.cards[0].capability={k:'parcel',readingStyle:'surface',parcelPlace:'家门口',parcels};const pkg=templates.packageScene(JSON.stringify(state),'private');assert.equal(pkg.state.cards[0].capability.parcels.length,0);assert.equal(pkg.state.cards[0].capability.parcelPlace,'');assert.equal(pkg.state.cards[0].capability.readingStyle,'surface');assert.equal(state.cards[0].capability.parcels.length,5,'export does not mutate local records');
for(const ink of ['#262824','#FFFFFF','#777777','#AA4455','#FFDD00','#000000','#234567'])assert.ok(p.textContrast(ink,p.readingSurfaceColor(ink))>=4.5,'reading backing is chosen by actual text contrast');
const normalized=s.normalizeState({...s.defaultState(),cards:[{...new s.FridgeCard(),id:'bounded',capability:{k:'calendar',calendarOffset:999}}]});assert.equal(normalized.cards[0].capability.calendarOffset,120);
console.log('PASS capability framework: complete catalog; adaptive list budgets; protected photo reading insets; shape-safe presets; local labelled pickup parsing/merge/capacity; 44vp rendered/hit geometry; compact deep links; template locality; month migration');

const viewport=load('EditorViewport');for(const body of [220,260,300]){const pane=viewport.editorPreviewPaneHeight(body,true);assert.ok(pane>body-164,'short landscape gives usable height back to artwork');assert.ok(body-pane-16>=92,'one-line layers retain 44vp targets, heading and padding');const v=viewport.editorViewport(240,280,15,400,body+100,0,24,true,pane);assert.ok(v.scale*280>40,'rotated preview remains useful for placement');}
