const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync('previewer/shared-models.js','utf8'),ctx);
const s=ctx.FridgeCore.load('CardSchema'),d=ctx.FridgeCore.load('DepthComposition'),snap=ctx.FridgeCore.load('CardViewSnapshot'),pack=ctx.FridgeCore.load('TemplatePackage');
const a=Object.assign(new s.FridgeCard(),{id:'source',groupId:'g',z:9,shape:'subject',subjectPhoto:true,cutout:'file:///subject.png',depthGroup:true});
const b=Object.assign(new s.FridgeCard(),{id:'title',groupId:'g',z:3});
const other=Object.assign(new s.FridgeCard(),{id:'other',z:20});
const before=JSON.stringify([a,b,other]);let projected=d.depthRenderCards([a,b,other]);
assert.equal(projected.length,4);assert.equal(projected[0].depthPass,'base');assert.equal(projected[0].z,2.75);assert.equal(projected[2].depthPass,'foreground');assert.equal(projected[2].z,9.25);assert.equal(projected[2].id,'source::depth');assert.equal(d.depthOwner(projected[2]),a.id);
assert.equal(projected[1],b);assert.equal(projected[3],other);assert.equal(JSON.stringify([a,b,other]),before,'projection must not rewrite editable scene');
assert.equal(d.depthRenderCards([a,b,other])[2],projected[2],'unchanged projection keeps decoded/rendered source alive');
assert.equal(d.depthRenderCards([a]).length,1,'a single card never duplicates itself');
a.hidden=true;assert.equal(d.depthRenderCards([a,b]).length,2,'hidden source restores ordinary composition');a.hidden=false;
a.cutout='';assert.equal(d.depthRenderCards([a,b]).length,2,'missing source has safe fallback');a.cutout='file:///subject.png';
const el=Object.assign(new s.CanvasElement(),{id:'photo',kind:'image',src:'file:///original.jpg',depthForeground:'file:///foreground.png',depthEnabled:true,depthSourceAspect:2,depthCrop:{x:.25,y:.1,w:.5,h:.8}});
let box=d.depthPhotoBox(el,100,100);assert.equal(box.x,0);assert.equal(box.y,.1);assert.equal(box.w,1);assert.equal(box.h,.8);
box=d.depthPhotoBox(el,200,100);assert.equal(box.x,.25);assert.equal(box.w,.5);
el.depthSourceAspect=.5;box=d.depthPhotoBox(el,100,100);assert.equal(box.x,.25);assert.equal(box.y,-.3);assert.equal(box.h,1.6,'portrait Cover crop stays registered');
const state=new s.FridgeState();a.subjectDepth=true;a.depthCapabilityFront=true;a.elements=[el];state.cards=[a,b];
const normalized=s.normalizeState(JSON.parse(JSON.stringify(state)));assert.equal(normalized.cards[0].subjectDepth,true);assert.equal(normalized.cards[0].depthGroup,true);assert.equal(normalized.cards[0].elements[0].depthEnabled,true);assert.equal(normalized.cards[0].elements[0].depthForeground,el.depthForeground);
const cached=snap.cardRenderSnapshot(a);a.depthCapabilityFront=false;assert.notEqual(snap.cardRenderSnapshot(a),cached,'depth preference invalidates only changed snapshot');
assert.equal(snap.cardStorageShell(projected[2]).depthPass,'','runtime projection cannot persist');
const portrait=s.normalizeElement({...el,animated:true});assert.equal(portrait.depthEnabled,false,'animated photo cannot drift from a static mask');
const invalid=s.normalizeElement({...el,depthCrop:{x:9,y:NaN,w:-2,h:Infinity}});assert.ok(invalid.depthCrop.w>0&&invalid.depthCrop.h>0);assert.ok(Number.isFinite(d.depthPhotoBox(invalid,1,1).x));
ctx.FridgeMaterials={};vm.runInContext(fs.readFileSync('previewer/capabilities.js','utf8'),ctx);vm.runInContext(fs.readFileSync('previewer/renderer.js','utf8'),ctx);
a.elements=[];a.cutout='file:///subject.png';a.outline=[[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}]];b.elements=[Object.assign(new s.CanvasElement(),{id:'text',text:'DEPTH'})];
const portable=pack.packageScene(JSON.stringify(state),'');portable.state.cards[0].cutout='asset://0';portable.assets=[{key:'asset://0',extension:'.png',data:fs.readFileSync('tests/fixtures/freeze-local.png').toString('base64')}];
const restored=pack.readPackage(JSON.stringify(portable));assert.equal(restored.state.cards[0].depthGroup,true);assert.equal(restored.state.cards[0].subjectDepth,true);
const rendered=ctx.FridgeWeb.renderPackage(restored,400,Date.now());assert.ok(rendered.svg.includes('source::depth'));assert.ok(rendered.svg.indexOf('data-fridge-card="title"')<rendered.svg.indexOf('data-fridge-card="source::depth"'),'foreground paints above peer content');
const collision=Object.assign(new s.FridgeCard(),{id:'source::depth',z:50});const duplicated=d.depthRenderCards(restored.state.cards.concat([collision]));assert.equal(new Set(duplicated.map(c=>c.id)).size,duplicated.length);assert.equal(d.depthOwner(duplicated.find(c=>c.depthPass==='foreground')),'source');
const photoPack=JSON.parse(JSON.stringify(portable));photoPack.state.cards[0].shape='rect';photoPack.state.cards[0].subjectDepth=false;photoPack.state.cards[0].elements=[{...el,src:'asset://0',depthForeground:'asset://1',depthSourceAspect:2}];photoPack.assets.push({...photoPack.assets[0],key:'asset://1'});const photoRestored=pack.readPackage(JSON.stringify(photoPack));assert.equal(photoRestored.state.cards[0].elements[0].depthForeground,'asset://1');assert.equal(photoRestored.state.cards[0].elements[0].depthSourceAspect,2);photoPack.assets.pop();assert.throws(()=>pack.readPackage(JSON.stringify(photoPack)),/引用不完整/);
console.log('PASS depth: immutable/cached group projection, hidden/missing/single fallback, exact Cover registration, snapshot/persistence, GIF guard, normalization, portable package and browser stacking');
