const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ts=require('/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript'),m={exports:{}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(__dirname+'/../entry/src/main/ets/model/EditorScrollDetent.ets','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:m.exports,module:m});
const snap=new m.exports.EditorScrollDetent();
snap.begin(0,100);const small=snap.move(0,65,false,0);assert.ok(small<0&&small>-35);assert.equal(snap.finish(false),undefined,'short pull springs back');
snap.begin(0,100);const near=snap.move(0,20,false,0),far=snap.move(0,-60,false,0);assert.ok(Math.abs(far)<2*Math.abs(near),'resistance grows with distance');assert.equal(snap.finish(false),true,'only release commits expansion');assert.equal(snap.finish(true),undefined,'one decision per touch');
snap.begin(0,100);assert.equal(snap.move(0,220,true,50),0,'scrolling existing content cannot collapse');snap.move(0,260,true,0);assert.equal(snap.finish(true),undefined);
snap.begin(0,100);snap.move(0,200,true,0);assert.equal(snap.finish(true),false);
snap.begin(0,100);assert.equal(snap.move(150,30,false,0),0);assert.equal(snap.finish(false),undefined,'horizontal swipe never snaps');
snap.begin(0,100);snap.move(0,-100,false,0);snap.move(0,75,false,0);assert.equal(snap.finish(false),undefined,'reversing before release cancels commitment');
snap.begin(0,100);snap.move(0,-100,false,0);snap.end();assert.equal(snap.finish(false),undefined,'cancel/multitouch/inertia never snaps');
console.log('PASS editor detents: progressive resistance, release thresholds, reversal, scroll boundary and gesture cancellation');
