const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ts=require('/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript');
const root=path.resolve(__dirname,'../entry/src/main/ets/model'),cache=new Map();let jobs=0;const testFiles=new Set();let opens=0;
const pool={Task:class{constructor(fn,...args){this.fn=fn;this.args=args;}},execute:async task=>{jobs++;return task.fn(...task.args);}};
function load(name){const file=path.resolve(root,name+'.ets');if(cache.has(file))return cache.get(file).exports;const mod={exports:{}};cache.set(file,mod);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInThisContext('(function(require,module,exports){'+code+'\n})',{filename:file})(s=>s==='@kit.ArkTS'?{taskpool:pool}:s==='@kit.CoreFileKit'?{fileIo:{OpenMode:{READ_ONLY:0},open:async name=>{if(!testFiles.has(name))throw Error('no test files');return {fd:++opens};},closeSync:()=>{}}}:load(path.relative(root,path.resolve(path.dirname(file),s))),mod,mod.exports);return mod.exports;}
(async()=>{
const r=load('RenderContours'),s=load('CardSchema');
const source=new s.FridgeCard();source.id='photo';source.cutout='file://local.png';source.subjectVersion=2;source.shape='subject';source.outline=[[{x:.1,y:.1},{x:.9,y:.1},{x:.9,y:.9},{x:.1,y:.9}]];
const state=new s.FridgeState();state.cards=[source];await r.primeRenderContours([source],JSON.stringify(state));assert.equal(jobs,1);
const encoded=r.serializeContourCache([source]);assert.ok(encoded);assert.equal(r.serializeContourCache([]),'');
r.serializeContourCache([source]);
const stringify=JSON.stringify;let encodes=0;
JSON.stringify=(...args)=>{encodes++;return stringify(...args);};
try {
 for(let i=0;i<100;i++){source.x=i;source.rot=i;assert.equal(r.serializeContourCache([source]),encoded);}
 assert.equal(encodes,0,'placement-only saves must not re-encode immutable contour assets');
 source.subjectVersion++;assert.notEqual(r.serializeContourCache([source]),encoded);
 assert.equal(encodes,1,'new asset version invalidates serialized cache');source.subjectVersion--;
 assert.equal(r.serializeContourCache([source]),encoded);
 assert.equal(r.serializeContourCache([]),'','removed cards cannot survive in derived cache');
} finally {JSON.stringify=stringify;}
const fresh=()=>Object.assign(new s.FridgeCard(),JSON.parse(JSON.stringify(source)));
const restored=fresh();restored.id='duplicate';restored.w=70;restored.rot=40;assert.equal(r.restoreContourCache([restored],encoded),1,'same immutable asset survives duplication, resizing and rotation');
await r.primeRenderContours([restored],'');assert.equal(jobs,1,'cold cache hit dispatches no topology worker');
restored.renderContourKey=r.registerRenderContour(restored);restored.outline=[];assert.deepEqual(r.cardOutline(restored),source.outline);
const changed=fresh();changed.outline[0][1].x=.85;assert.equal(r.restoreContourCache([changed],encoded),0,'edited master geometry invalidates cache');
const newVersion=fresh();newVersion.subjectVersion++;assert.equal(r.restoreContourCache([newVersion],encoded),0);
for(const raw of ['broken','{}',JSON.stringify({...JSON.parse(encoded),version:99})])assert.equal(r.restoreContourCache([fresh()],raw),0,'disposable cache cannot prevent local scene loading');
const corrupt=JSON.parse(encoded);Object.values(corrupt.entries)[0].outline[0][0].x=null;assert.equal(r.restoreContourCache([fresh()],JSON.stringify(corrupt)),0);
state.cards=[changed];await r.primeRenderContours([changed],JSON.stringify(state));assert.equal(jobs,2,'changed artwork is reprocessed off the UI thread');
const geometry=load('ContourGeometry');const originalCompact=geometry.compactContours;let compactions=0;
geometry.compactContours=(...args)=>{compactions++;return originalCompact(...args);};
const widget=fresh();widget.id='widget-prepared';r.registerRenderContour(widget,true);
assert.equal(compactions,0,'provider-prepared geometry is never recomputed in Form rendering');
assert.equal(r.cardOutline({...widget,outline:[],renderContourKey:r.registerRenderContour(widget,true)}),widget.outline);
const app=fresh();app.id='app-unprepared';r.registerRenderContour(app);
assert.equal(compactions,1,'unprepared app outlines retain topology validation');
const payload=load('WidgetPayload');const beforePayload=compactions;
const prepared=await payload.prepareWidgetPayload(JSON.stringify(state),r.serializeContourCache(state.cards));
assert.equal(compactions,beforePayload,'exact cached master skips provider recompression');
assert.equal(JSON.parse(prepared.cards)[0].outline.length,changed.outline.length);
await payload.prepareWidgetPayload(JSON.stringify(state),'{invalid');
assert.equal(compactions,beforePayload+1,'broken cache rebuilds safely');
const stale=JSON.parse(r.serializeContourCache(state.cards));Object.values(stale.entries)[0].source='stale';
await payload.prepareWidgetPayload(JSON.stringify(state),JSON.stringify(stale));
assert.equal(compactions,beforePayload+2,'stale geometry cannot be reused');
geometry.compactContours=originalCompact;
testFiles.add('local.png');testFiles.add('/cache/relief.png');const reliefMap=JSON.stringify({[changed.id]:'file:///cache/relief.png'});
const initial=await payload.prepareWidgetPayload(JSON.stringify(state),'','',reliefMap);
assert.equal(Object.keys(initial.images).length,2,'Form sends subject and relief together');assert.ok(JSON.parse(initial.cards)[0].reliefSrc.startsWith('memory://'));
const count=opens,reused=await payload.prepareWidgetPayload(JSON.stringify(state),'',initial.manifest,reliefMap);
assert.equal(opens,count,'unchanged relief reuses native Form cache without reopening files');assert.deepEqual(reused.images,{});
testFiles.add('/cache/resized.png');const resized=await payload.prepareWidgetPayload(JSON.stringify(state),'',initial.manifest,JSON.stringify({[changed.id]:'file:///cache/resized.png'}));
assert.equal(Object.keys(resized.images).length,2,'geometry changes atomically replace all Form images');
const layout=load('CanvasLayout'),photo=new s.FridgeCard();
photo.id='layout-photo';photo.shape='subject';photo.cutout='file://layout-photo.png';photo.subjectVersion=4;photo.w=240;photo.h=300;photo.capability={k:'clock'};
photo.outline=[Array.from({length:512},(_,i)=>({x:.5+.48*Math.cos(i*Math.PI/256),y:.5+.48*Math.sin(i*Math.PI/256)}))];
const geometryBefore=JSON.stringify([photo.w,photo.h,photo.capBox]);
const layoutJson=layout.warmStartupLayouts([photo]),expected=layout.capabilityPlacement(photo);
assert.equal(JSON.stringify([photo.w,photo.h,photo.capBox]),geometryBefore,'prewarming must not mutate stored user geometry');
cache.delete(path.resolve(root,'CanvasLayout.ets'));const restoredLayout=load('CanvasLayout');restoredLayout.restoreStartupLayouts(layoutJson);
photo.outline=photo.outline.map(loop=>loop.map(point=>({get x(){throw Error('outline rescanned');},get y(){throw Error('outline rescanned');}})));
assert.deepEqual(JSON.parse(JSON.stringify(restoredLayout.capabilityPlacement(photo))),JSON.parse(JSON.stringify(expected)),'restored worker geometry matches placement without rescanning any silhouette point');
assert.doesNotThrow(()=>restoredLayout.minimumCardSize(photo));
photo.subjectVersion++;assert.throws(()=>restoredLayout.minimumCardSize(photo),/outline rescanned/,'new asset version must invalidate worker geometry');
console.log('PASS startup layout handoff: immutable geometry, exact placement, no UI contour scanning and asset-version invalidation');
console.log('PASS cold contour cache: exact-source/asset matching, worker avoidance, geometry reuse, corruption/version fallback and edit invalidation');
})().catch(e=>{console.error(e);process.exitCode=1;});
