const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ts=require('/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript');
const panel=fs.readFileSync('entry/src/main/ets/views/SceneSchedulePanel.ets','utf8'),index=fs.readFileSync('entry/src/main/ets/pages/Index.ets','utf8');
const core=vm.createContext({});vm.runInContext(fs.readFileSync('previewer/shared-models.js','utf8'),core);const schema=core.FridgeCore.load('SceneScheduleSchema');
let timeOptions,dateOptions;const moduleMock={exports:{}};
const methods=panel.slice(panel.indexOf('  private edit(rule:'),panel.indexOf('  private saveRotation('));
vm.runInNewContext(ts.transpileModule(`class Fixture {mounted=true;editingRule=false;draft=new SceneRule();draftStart=1200;draftDate='';draftName='';draftEnabled=true;draftRepeat='daily';draftWeekdays=[0,1,2,3,4,5,6];draftTimeout=15;contentScroller={scrollTo:()=>{}};getUIContext(){return {animateTo:(options,update)=>update(),showTimePickerDialog:v=>TimePickerDialog.show(v),showDatePickerDialog:v=>DatePickerDialog.show(v)};}${methods}} module.exports=Fixture;`,{compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText,{module:moduleMock,settingsExpansionMotion:()=>({duration:220}),SceneRule:schema.SceneRule,sceneDay:schema.sceneDay,Date,TimePickerDialog:{show:v=>timeOptions=v},DatePickerDialog:{show:v=>dateOptions=v}});
const f=new moduleMock.exports(),rule=new schema.SceneRule();rule.id='rule';rule.targetId='scene';rule.centralOnly=true;f.edit(rule);f.pickTime();timeOptions.onAccept({hour:8,minute:37});assert.equal(f.draftStart,517);assert.equal(rule.start,1200,'stored rule is untouched before save');f.pickDate();dateOptions.onAccept({year:2026,month:9,day:12});assert.equal(f.draftDate,'2026-10-12');const saved=schema.normalizeSceneRules([f.draftRule()])[0];assert.equal(saved.start,517);assert.equal(saved.date,'2026-10-12');f.edit(saved);assert.equal(f.draftStart,517,'reopening restores saved time');f.pickTime();f.edit({...saved,id:'other'});timeOptions.onAccept({hour:12,minute:0});assert.equal(f.draftStart,517,'stale picker cannot edit a different rule');f.pickDate();f.mounted=false;dateOptions.onAccept({year:2027,month:0,day:1});assert.equal(f.draftDate,'2026-10-12','closed panel ignores pending date selection');
// Execute the real canvas header callback: closing a background panel must retain
// the scene document, and reopening the picker must not invoke scene completion.
const marker=".accessibilityText('切换画布 '+this.canvasName)",start=index.indexOf('.onClick(()=>{',index.indexOf(marker))+14,end=index.indexOf('})',start);const body=index.slice(start,end);
let exits=0;const home={sceneEditing:true,canvasChanging:false,scheduleOpen:false,backgroundOpen:true,canvasPickerOpen:false,canvasCreating:false,canvasRenameId:'',homeToolsOpen:false,leaveTimedScene:()=>exits++,refreshCanvasList:()=>{},floatingHome:()=>false};const click=new Function("const floating=false;"+body);click.call(home);assert.equal(home.backgroundOpen,false);assert.equal(home.sceneEditing,true);assert.equal(exits,0);click.call(home);assert.equal(home.canvasPickerOpen,true);assert.equal(home.sceneEditing,true);assert.equal(exits,0);
assert(panel.includes('Button(sceneClock(this.draftStart)'),'time label reads reactive state directly rather than a value-captured builder');assert(panel.includes('Button(this.draftDate'));
assert(!panel.includes("bindMenu([{value:'删除场景'"),'deletion is directly discoverable');assert(panel.includes("accessibilityText('删除场景 '"));assert(index.includes("onRemove:id=>this.confirmDeleteTimedScene(id)"));
console.log('PASS scene editor: observable time/date draft, normalized save and background/picker navigation retains the scene');
