const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),vm=require('node:vm');
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync('previewer/shared-models.js','utf8'),ctx);const core=ctx.FridgeCore;
const fixture='skills/fridge-create/examples/static/silhouette.fridge',raw=JSON.parse(fs.readFileSync(fixture,'utf8'));const card=core.load('TemplatePackage').readPackage(JSON.stringify(raw)).state.cards[0];
assert.equal(card.shape,'subject');assert.equal(card.subjectPhoto,false,'mask-only avoids drawing appearance twice');assert(card.outline.length>0);assert.equal(card.elements[0].opacity,1);assert.equal(card.html.previewElementId,card.elements[0].id);assert(card.html.source.includes('clipPath'));assert.equal(card.capability.k,'clock');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'fridge-compose-test-'));
try{
 const privateCopy=JSON.parse(JSON.stringify(raw));privateCopy.state.cards[0].capability={k:'agenda',events:[{id:'secret',title:'Private',start:1,end:2,location:'Home'}],updatedAt:3};
 fs.writeFileSync(path.join(temp,'private.fridge'),JSON.stringify(privateCopy));const manifest={canvasAspect:1,background:{mode:'transparent',frameStyle:'light',frameMaterial:'oak'},cards:[{file:path.resolve(fixture),x:20,y:30,w:200,h:140,groupId:'pair'},{file:'private.fridge',x:100,y:250,w:200,h:140,groupId:'pair'}]};
 fs.writeFileSync(path.join(temp,'manifest.json'),JSON.stringify(manifest));const out=path.join(temp,'canvas.fridge');cp.execFileSync(process.execPath,['scripts/fridge-compose.cjs',path.join(temp,'manifest.json'),out]);const combined=JSON.parse(fs.readFileSync(out,'utf8'));core.load('TemplatePackage').readPackage(JSON.stringify(combined));
 assert.equal(combined.state.background.frameMaterial,'oak');assert.equal(combined.state.cards.length,2);assert.equal(combined.assets.length,2);assert.notEqual(combined.state.cards[0].id,combined.state.cards[1].id);assert.notEqual(combined.state.cards[0].html.previewElementId,combined.state.cards[1].html.previewElementId);assert.notEqual(combined.state.cards[0].elements[0].src,combined.state.cards[1].elements[0].src);assert.equal(combined.state.cards[1].capability.events.length,0);assert(!JSON.stringify(combined).includes('Private'));assert.equal(combined.state.cards[0].groupId,'pair');
 console.log('PASS static source/mask/cache, editable composition, independent IDs/assets/groups, current frame materials and recipient-data sanitization');
}finally{fs.rmSync(temp,{recursive:true,force:true});}
