const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ts=require(process.env.FRIDGE_TYPESCRIPT||'/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript');
const root=path.resolve(__dirname,'../entry/src/main/ets/model'),cache=new Map(),files=new Map(),fds=new Map();let fd=0;
const io={OpenMode:{READ_ONLY:0,CREATE:1,READ_WRITE:2,TRUNC:4},openSync(p,mode){p=p.replace(/^file:\/\//,'');if(mode){files.set(p,Buffer.alloc(0));}if(!files.has(p))throw Error('missing');fds.set(++fd,p);return{fd};},statSync(d){return{size:files.get(fds.get(d)).length};},readSync(d,b,o){const src=files.get(fds.get(d)),n=Math.min(b.byteLength,src.length-o.offset);new Uint8Array(b).set(src.subarray(o.offset,o.offset+n));return n;},writeSync(d,b,o){const p=fds.get(d),out=Buffer.alloc(Math.max(files.get(p).length,o.offset+b.byteLength));files.get(p).copy(out);Buffer.from(b).copy(out,o.offset);files.set(p,out);return b.byteLength;},closeSync(d){fds.delete(d);},unlinkSync(p){files.delete(p);}};
const kits={'@kit.CoreFileKit':{fileIo:io},'@kit.ArkTS':{util:{Base64Helper:class{encodeToStringSync(b){return Buffer.from(b).toString('base64');}decodeSync(s){return new Uint8Array(Buffer.from(s,'base64'));}},TextEncoder:class{encodeInto(s){return new TextEncoder().encode(s);}},TextDecoder:class{decodeWithStream(b){return new TextDecoder().decode(b);}}}}};
function load(name){if(cache.has(name))return cache.get(name);const module={exports:{}};cache.set(name,module.exports);const code=ts.transpileModule(fs.readFileSync(path.join(root,name+'.ets'),'utf8').replace(/^@Concurrent\s*$/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInThisContext('(function(require,module,exports){'+code+'\n})', {filename:name})(s=>kits[s]||load(s.replace('./','')),module,module.exports);cache.set(name,module.exports);return module.exports;}
(async()=>{
 const {FridgeCard,CanvasElement,defaultState}=load('CardSchema'),{packageScene,readPackage,importedCards,fitImportedCanvas}=load('TemplatePackage'),{exportTemplate,materializeTemplateUri,inspectTemplate}=load('TemplateFiles');
 const scene=defaultState(),a=new FridgeCard(),b=new FridgeCard(),el=new CanvasElement();a.id='a';b.id='b';a.groupId=b.groupId='oldgroup';a.cutout='file:///private/subject.png';a.shape='subject';a.subjectPhoto=true;el.id='el';el.kind='image';el.src='file:///private/anim.gif';a.elements=[el];b.capability={k:'album',title:'Test Album',artist:'Artist',albumCover:'file:///private/subject.png',albumBackground:'file:///private/subject.png'};scene.cards=[a,b];scene.background.mode='photo';scene.background.src=scene.background.photo='file:///private/subject.png';
 files.set('/private/subject.png',Buffer.from([137,80,78,71,0,255]));files.set('/private/anim.gif',Buffer.from('GIF89a\0\xff','latin1'));
 const single=packageScene(JSON.stringify(scene),'a');assert.equal(single.state.cards.length,1);assert.equal(single.state.cards[0].groupId,'');assert.equal(single.state.background.src,'');assert.equal(scene.cards[0].groupId,'oldgroup');
 const out=await exportTemplate(JSON.stringify(scene),'','/private','/cache'),json=files.get(out).toString(),pack=readPackage(json);assert.equal(pack.assets.length,2,'shared image embedded once');assert.equal(pack.state.cards[0].cutout,'asset://0');assert.equal(pack.state.background.src,'asset://0');assert.ok(!json.includes('/private/'),'no sender sandbox paths');
 assert.deepEqual(JSON.parse(await inspectTemplate('file://'+out)),{kind:'canvas',count:2,images:2});
 const beforeRejected=files.size;
 await assert.rejects(()=>materializeTemplateUri('file://'+out,'/recipient',1),/最多 16/);
 assert.equal(files.size,beforeRejected,'capacity checked before extracting image files');
 const tooMany=JSON.parse(json);tooMany.state.cards=Array.from({length:17},(_,i)=>({...tooMany.state.cards[0],id:'over_'+i}));
 assert.throws(()=>readPackage(JSON.stringify(tooMany)),/最多 16/);
 const result=JSON.parse(await materializeTemplateUri('file://'+out,'/recipient'));assert.ok(result.cards[0].cutout.startsWith('file:///recipient/'));assert.deepEqual(files.get(result.cards[0].cutout.slice(7)),Buffer.from([137,80,78,71,0,255]));assert.deepEqual(files.get(result.cards[0].elements[0].src.slice(7)),Buffer.from('GIF89a\0\xff','latin1'),'GIF bytes survive unchanged');assert.equal(result.background.src,result.cards[0].cutout);assert.equal(result.cards[1].capability.albumCover,result.cards[0].cutout);assert.equal(result.cards[1].capability.albumBackground,result.cards[0].cutout);assert.equal(result.cards[1].capability.artist,'Artist');
 const fit=[Object.assign(new FridgeCard(),{x:30,y:100,w:120,h:200,rot:45})];fitImportedCanvas(fit,1,2);assert.equal(fit[0].w,60);assert.equal(fit[0].h,100);assert.equal(fit[0].x,101);assert.equal(fit[0].y,100);assert.equal(fit[0].rot,45,'fit preserves angles and artwork aspect');
 let n=0;const c1=importedCards(result,()=>String(++n)),c2=importedCards(result,()=>String(++n));assert.equal(c1[0].groupId,c1[1].groupId);assert.notEqual(c1[0].groupId,c2[0].groupId);assert.notEqual(c1[0].elements[0].id,c2[0].elements[0].id);assert.notEqual(c1[0].id,c2[0].id);
 for(const mutate of [p=>p.version=99,p=>p.assets[0].extension='../evil',p=>p.assets.push(p.assets[0]),p=>p.state.cards[0].cutout='file:///recipient/import_existing.png',p=>p.assets=[]]){const bad=JSON.parse(json);mutate(bad);assert.throws(()=>readPackage(JSON.stringify(bad)));}
 await assert.rejects(()=>exportTemplate(JSON.stringify({...scene,cards:[{...a,cutout:'file:///private/missing.png'}]}),'','/private','/cache'));
 assert.equal(fds.size,0,'all file descriptors released');console.log('PASS: editable card/canvas packages; all image bytes and GIF preserved; image deduplication; sender paths removed; subject/background asset keys survive normalization; groups and every ID remapped; unsupported/truncated references rejected; missing file aborts export; descriptors released.');
})().catch(e=>{console.error(e);process.exitCode=1;});
